#define MOD_PRESET_DEFAULT list( \
			HELMET_LAYER = NECK_LAYER,\
			HELMET_FLAGS = list( \
				UNSEALED_CLOTHING = NONE,\
				SEALED_CLOTHING = THICKMATERIAL|STOPSPRESSUREDAMAGE|ALLOWINTERNALS,\
				UNSEALED_INVISIBILITY = HIDEFACIALHAIR,\
				SEALED_INVISIBILITY = HIDEMASK|HIDEEARS|HIDEEYES|HIDEFACE|HIDEHAIR,\
				SEALED_COVER = HEADCOVERSMOUTH|HEADCOVERSEYES,\
			),\
			CHESTPLATE_FLAGS = list( \
				UNSEALED_CLOTHING = THICKMATERIAL,\
				SEALED_CLOTHING = STOPSPRESSUREDAMAGE,\
				SEALED_INVISIBILITY = HIDEJUMPSUIT,\
			),\
			GAUNTLETS_FLAGS = list(\
				UNSEALED_CLOTHING = THICKMATERIAL,\
				SEALED_CLOTHING = STOPSPRESSUREDAMAGE,\
			),\
			BOOTS_FLAGS = list(\
				UNSEALED_CLOTHING = THICKMATERIAL,\
				SEALED_CLOTHING = STOPSPRESSUREDAMAGE,\
			),\
		)\

#define MOD_PRESET_WITHOUT_PRESSURE_PROTECT list( \
			HELMET_LAYER = NECK_LAYER,\
			HELMET_FLAGS = list( \
				UNSEALED_CLOTHING = NONE,\
				SEALED_CLOTHING = THICKMATERIAL|ALLOWINTERNALS,\
				UNSEALED_INVISIBILITY = HIDEFACIALHAIR,\
				SEALED_INVISIBILITY = HIDEMASK|HIDEEARS|HIDEEYES|HIDEFACE|HIDEHAIR,\
				SEALED_COVER = HEADCOVERSMOUTH|HEADCOVERSEYES,\
			),\
			CHESTPLATE_FLAGS = list( \
				UNSEALED_CLOTHING = THICKMATERIAL,\
				SEALED_INVISIBILITY = HIDEJUMPSUIT,\
			),\
			GAUNTLETS_FLAGS = list( \
				UNSEALED_CLOTHING = THICKMATERIAL,\
			),\
			BOOTS_FLAGS = list( \
				UNSEALED_CLOTHING = THICKMATERIAL,\
			),\
		),\

#define MOD_PRESET_WITHOUT_PRESSURE_PROTECT_NO_JUMSUIT_HIDE list( \
			HELMET_LAYER = NECK_LAYER,\
			HELMET_FLAGS = list( \
				UNSEALED_CLOTHING = NONE,\
				SEALED_CLOTHING = THICKMATERIAL|ALLOWINTERNALS,\
				UNSEALED_INVISIBILITY = HIDEFACIALHAIR,\
				SEALED_INVISIBILITY = HIDEMASK|HIDEEARS|HIDEEYES|HIDEFACE|HIDEHAIR,\
				SEALED_COVER = HEADCOVERSMOUTH|HEADCOVERSEYES,\
			),\
			CHESTPLATE_FLAGS = list( \
				UNSEALED_CLOTHING = THICKMATERIAL,\
				SEALED_INVISIBILITY = null, \
			),\
			GAUNTLETS_FLAGS = list( \
				UNSEALED_CLOTHING = THICKMATERIAL,\
			),\
			BOOTS_FLAGS = list( \
				UNSEALED_CLOTHING = THICKMATERIAL,\
			),\
		),\
