/// Infestation from changeling absorb husks — «мини»-угроза после высасывания.
#define CHANGELING_ZOMBIE_TOXINS_THRESHOLD_TO_TRANSFORM 100
#define CHANGELING_ZOMBIE_MINIMUM_TRANSFORM_DELAY (30 SECONDS)
#define CHANGELING_ZOMBIE_TOXINS_THRESHOLD_TO_CURE 50
#define CHANGELING_ZOMBIE_TOXINS_PER_SECOND_LIVING 0.5
#define CHANGELING_ZOMBIE_TOXINS_PER_SECOND_DEAD 1.5
#define CHANGELING_ZOMBIE_INFECT_CHANCE 80
#define CHANGELING_ZOMBIE_INFECT_CHANCE_LESSER 5
#define CHANGELING_ZOMBIE_REINFECT_DELAY (3 SECONDS)
#define CHANGELING_ZOMBIE_PASSIVE_HEALING 3
#define CHANGELING_ZOMBIE_LIMB_REGEN_TIME (30 SECONDS)

#define TRAIT_CHANGELING_ZOMBIE "changeling_zombie"
