#define ANTAG_TRAINING_SIZE 55
#define ANTAG_TRAINING_MAX_ARENAS 1
#define ANTAG_TRAINING_DISCONNECT_GRACE (1 MINUTES)
#define ANTAG_TRAINING_TARGET_LIMIT 12
#define ANTAG_TRAINING_SUPPLY_LIMIT 100
#define ANTAG_TRAINING_STRUCTURE_LIMIT 16
#define ANTAG_TRAINING_WORK_BUDGET_MS 5
// В тестах stoplag() не ждёт свободного тика, и гейт не должен: МК держит тик занятым минутами.
#ifdef UNIT_TESTS
#define ANTAG_TRAINING_TICK_FREE TRUE
#else
#define ANTAG_TRAINING_TICK_FREE (TICK_USAGE < TICK_LIMIT_TO_RUN)
#endif
#define ANTAG_TRAINING_RESTART_DELAY (5 SECONDS)
#define ANTAG_TRAINING_VOTE_TIME (45 SECONDS)
#define ANTAG_TRAINING_BATCH_LIMIT 12
#define ANTAG_TRAINING_POINTS 100
#define ANTAG_TRAINING_PRACTICE_DELAY (5 SECONDS)
#define ANTAG_TRAINING_DUEL_INVITE (30 SECONDS)
#define ANTAG_TRAINING_DUEL_COUNTDOWN (3 SECONDS)
#define ANTAG_TRAINING_DUEL_DURATION (3 MINUTES)
#define ANTAG_TRAINING_SPAWN_RADIUS 3
#define ANTAG_TRAINING_KNOCKDOWN (10 SECONDS)
#define ANTAG_TRAINING_RUNNER_STEP (0.4 SECONDS)
