#define HERETIC_MANSUS_ROOM_SIZE 33
#define HERETIC_MANSUS_GRID 4
#define HERETIC_MANSUS_CELL 7
#define HERETIC_MANSUS_CELL_STRIDE 8
#define HERETIC_MANSUS_EXTRA_EDGES 3
#define HERETIC_MANSUS_DURATION (180 SECONDS)
#define HERETIC_MANSUS_RECALL_TIME (2 SECONDS)
#define HERETIC_MANSUS_MEMORIES 3
#define HERETIC_MANSUS_WARNING_TIME (2 SECONDS)
#define HERETIC_MANSUS_HAZARD_LIFETIME (3 SECONDS)
#define HERETIC_MANSUS_HAZARD_LINE 5
#define HERETIC_MANSUS_HIT_GRACE (4 SECONDS)
#define HERETIC_MANSUS_HUNTER_GRACE (3 SECONDS)
#define HERETIC_MANSUS_GATE_SAFETY 1
#define HERETIC_MANSUS_TRAIL_LENGTH 3
#define HERETIC_MANSUS_TRAIL_CARRY_LENGTH 2
#define HERETIC_MANSUS_FINAL_PRESSURE 2
#define HERETIC_MANSUS_HUNTER_STEP (1 SECONDS)
#define HERETIC_MANSUS_HUNTER_FAST_STEP (0.5 SECONDS)
#define HERETIC_MANSUS_HUNTER_DISTANCE 6
#define HERETIC_MANSUS_SIGHT_RANGE 7
#define HERETIC_MANSUS_SEARCH_RANGE 10
#define HERETIC_MANSUS_DISPEL_DELAY (8 SECONDS)
#define HERETIC_MANSUS_NAME_RANGE 5
#define HERETIC_MANSUS_NAME_CLEAR_RANGE 2
#define HERETIC_MANSUS_PENALTY_PER_MEMORY (60 SECONDS)
#define HERETIC_MANSUS_ALERT "heretic_mansus"
#define HERETIC_MANSUS_ECHO_TINT list(0.79, 0, 0, 0, 0.79, 0, 0, 0, 0.79, 0, 0, 0, 0.12, 0.12, 0.12)
#define HERETIC_MANSUS_RULES_ICON 'modular_bluemoon/icons/obj/heretic_mansus_rules.dmi'
#define HERETIC_MANSUS_GUIDANCE_ICON 'modular_bluemoon/icons/obj/heretic_mansus_guidance.dmi'
