compressionLevel: mixed

enableGlobalCache: false
enableMirror: false
globalFolder: .yarn/global

enableScripts: false
cacheFolder: .yarn/cache

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

packageExtensions:
  babel-plugin-inferno@*:
    peerDependencies:
      "@babel/core": "*"
  eslint-plugin-sonarjs@*:
    dependencies:
      ts-api-utils: "^2.4.0"

pnpEnableEsmLoader: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.12.0.cjs
