/obj/vehicle/sealed/mecha/combat/durand/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/weapon/ballistic/lmg(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/repair_droid(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/antiproj_armor_booster(src)
	ME.attach(src)
	max_ammo()

/obj/vehicle/sealed/mecha/combat/gygax/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/weapon/ballistic/lmg(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/thrusters/ion(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/tesla_energy_relay(src)
	ME.attach(src)
	max_ammo()

/obj/vehicle/sealed/mecha/medical/odysseus/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/medical/mechmedbeam(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/medical/syringe_gun(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/medical/sleeper(src)
	ME.attach(src)

/obj/vehicle/sealed/mecha/medical/medigax/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/medical/mechmedbeam(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/thrusters/ion(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/medical/sleeper(src)
	ME.attach(src)

/obj/vehicle/sealed/mecha/working/ripley/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/drill(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/thrusters/ion(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/tesla_energy_relay(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/hydraulic_clamp(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/rcd(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/extinguisher(src)
	ME.attach(src)

/obj/vehicle/sealed/mecha/working/ripley/mkii/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/drill/diamonddrill(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/hydraulic_clamp(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/weapon/energy/plasma(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/mining_scanner(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/tesla_energy_relay(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/anticcw_armor_booster(src)
	ME.attach(src)

/obj/vehicle/sealed/mecha/working/ripley/firefighter/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/drill/diamonddrill(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/thrusters/ion(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/tesla_energy_relay(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/hydraulic_clamp(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/rcd(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/extinguisher(src)
	ME.attach(src)

/obj/vehicle/sealed/mecha/proc/install_titanfall_premium_parts()
	QDEL_NULL(cell)
	QDEL_NULL(scanmod)
	QDEL_NULL(capacitor)
	add_cell(new /obj/item/stock_parts/cell/bluespace(src))
	add_scanmod(new /obj/item/stock_parts/scanning_module/unilatera_triphasic(src))
	add_capacitor(new /obj/item/stock_parts/capacitor/giga(src))
	update_part_values()
	diag_hud_set_mechcell()
	diag_hud_set_mechstat()
	install_titanfall_tracker_if_missing()

/obj/vehicle/sealed/mecha/proc/install_titanfall_tracker_if_missing()
	if(LAZYLEN(trackers))
		return
	var/obj/item/mecha_parts/mecha_tracking/MT = new /obj/item/mecha_parts/mecha_tracking(src)
	MT.attach(src)

/obj/item/choice_beacon/vehicle/create_choice_atom(atom/choice, mob/owner)
	. = ..()
	if(istype(., /obj/vehicle/sealed/mecha))
		var/obj/vehicle/sealed/mecha/beacon_mech = .
		beacon_mech.install_titanfall_premium_parts()
