#define CUSTOM_INTERACTION_PREFIX "custom:"
#define MAX_CUSTOM_INTERACTIONS 5
#define MAX_CUSTOM_INTERACTIONS_SUBSCRIBER 10
#define MAX_CUSTOM_INTERACTIONS_SPONSOR 15
#define MAX_CUSTOM_INTERACTION_NAME_LENGTH 100
#define MAX_CUSTOM_INTERACTION_MESSAGE_LENGTH 500

#define CUSTOM_INTERACTION_TYPE_NORMAL "normal"
#define CUSTOM_INTERACTION_TYPE_LEWD "lewd"
#define CUSTOM_INTERACTION_TYPE_EXTREME "extreme"
#define CUSTOM_INTERACTION_TYPE_UNHOLY "unholy"
#define CUSTOM_INTERACTION_TYPES list(CUSTOM_INTERACTION_TYPE_NORMAL, CUSTOM_INTERACTION_TYPE_LEWD, CUSTOM_INTERACTION_TYPE_EXTREME, CUSTOM_INTERACTION_TYPE_UNHOLY)

#define CUSTOM_AROUSAL_NONE 0
#define CUSTOM_AROUSAL_LIGHT 1
#define CUSTOM_AROUSAL_MEDIUM 2
#define CUSTOM_AROUSAL_STRONG 3
#define CUSTOM_AROUSAL_MAX CUSTOM_AROUSAL_STRONG
