#define CUSTOM_INTERACTION_PREFIX "custom:"
#define MAX_CUSTOM_INTERACTIONS 10
#define MAX_CUSTOM_INTERACTIONS_SUBSCRIBER 15
#define MAX_CUSTOM_INTERACTIONS_SPONSOR 25
#define MAX_CUSTOM_INTERACTION_NAME_LENGTH 100
#define MAX_CUSTOM_INTERACTION_MESSAGE_LENGTH 500

#define CUSTOM_INTERACTION_TYPE_NORMAL "normal"
#define CUSTOM_INTERACTION_TYPE_LEWD "lewd"
#define CUSTOM_INTERACTION_TYPE_EXTREME "extreme"
#define CUSTOM_INTERACTION_TYPE_UNHOLY "unholy"
#define CUSTOM_INTERACTION_TYPES list(CUSTOM_INTERACTION_TYPE_NORMAL, CUSTOM_INTERACTION_TYPE_LEWD, CUSTOM_INTERACTION_TYPE_EXTREME, CUSTOM_INTERACTION_TYPE_UNHOLY)

#define CUSTOM_INTERACTION_SCOPE_SELF "self"
#define CUSTOM_INTERACTION_SCOPE_BOTH "both"
#define CUSTOM_INTERACTION_SCOPE_OTHERS "others"
#define CUSTOM_INTERACTION_SCOPES list(CUSTOM_INTERACTION_SCOPE_SELF, CUSTOM_INTERACTION_SCOPE_BOTH, CUSTOM_INTERACTION_SCOPE_OTHERS)

#define CUSTOM_INTERACTION_BODY_PART_REQUIREMENTS list(INTERACTION_REQUIRE_ANUS, INTERACTION_REQUIRE_BALLS, INTERACTION_REQUIRE_BELLY, INTERACTION_REQUIRE_BREASTS, INTERACTION_REQUIRE_EARS, INTERACTION_REQUIRE_EYES, INTERACTION_REQUIRE_FEET, INTERACTION_REQUIRE_PENIS, INTERACTION_REQUIRE_VAGINA, INTERACTION_REQUIRE_TAIL)
#define CUSTOM_INTERACTION_BODY_PART_MASK (INTERACTION_REQUIRE_ANUS | INTERACTION_REQUIRE_BALLS | INTERACTION_REQUIRE_BELLY | INTERACTION_REQUIRE_BREASTS | INTERACTION_REQUIRE_EARS | INTERACTION_REQUIRE_EYES | INTERACTION_REQUIRE_FEET | INTERACTION_REQUIRE_PENIS | INTERACTION_REQUIRE_VAGINA | INTERACTION_REQUIRE_TAIL)

#define CUSTOM_AROUSAL_NONE 0
#define CUSTOM_AROUSAL_LIGHT 1
#define CUSTOM_AROUSAL_MEDIUM 2
#define CUSTOM_AROUSAL_STRONG 3
#define CUSTOM_AROUSAL_MAX CUSTOM_AROUSAL_STRONG
