/// Каждый путь бесплатно выдаёт свою черту и описывает её в книге.
/datum/unit_test/heretic_innates/Run()
	var/obj/item/forbidden_book/book = allocate(/obj/item/forbidden_book)
	var/list/catalog = book.ui_static_data(null)
	var/list/innate_types = list()
	for(var/path_id in GLOB.heretic_paths)
		var/datum/heretic_path/path = GLOB.heretic_paths[path_id]
		var/datum/antagonist/heretic/heretic = allocate_heretic()
		heretic.knowledge_points = 0
		TEST_ASSERT(heretic.research_knowledge(path.knowledge[1], heretic.owner.current), "Путь [path_id] выбирается бесплатно.")
		var/datum/eldritch_knowledge/knowledge = heretic.get_knowledge(path.knowledge[1])
		TEST_ASSERT(istype(knowledge.innate, path.innate_type), "[path_id] выдаёт свою черту.")
		TEST_ASSERT(knowledge.innate.valid(), "[path_id]: черта работает сразу после выбора.")
		TEST_ASSERT(!(path.innate_type in innate_types), "У путей разные черты.")
		innate_types += path.innate_type
		var/found_description = FALSE
		for(var/list/entry as anything in catalog["paths"])
			if(entry["id"] == path_id)
				found_description = entry["innate_name"] == knowledge.innate.name && length(entry["innate_desc"])
		TEST_ASSERT(found_description, "[path_id]: книга описывает врождённую черту.")
		TEST_ASSERT_EQUAL(heretic.knowledge_points, 0, "Черта не стоит очков.")

/datum/unit_test/heretic_innates/proc/create_path(path_id)
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = path_id
	var/datum/heretic_path/path = GLOB.heretic_paths[path_id]
	heretic.gain_knowledge(path.knowledge[1])
	var/datum/eldritch_knowledge/knowledge = heretic.get_knowledge(path.knowledge[1])
	return knowledge.innate

/datum/unit_test/heretic_innates/proc/create_victim()
	var/mob/living/carbon/human/victim = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	victim.mind_initialize()
	return victim

/// Боевые черты соблюдают условия, пределы и перезарядку.
/datum/unit_test/heretic_innates/combat/Run()
	var/mob/living/carbon/human/victim = create_victim()
	var/datum/heretic_innate/ash/ash = create_path(PATH_ASH)
	ash.body.adjustFireLoss(10)
	ash.blade_hit(victim, 20)
	TEST_ASSERT_EQUAL(round(ash.body.getFireLoss(), DAMAGE_PRECISION), 10, "Негорящий враг не питает Пепел.")
	victim.adjust_fire_stacks(3)
	victim.IgniteMob()
	ash.blade_hit(victim, 20)
	ash.blade_hit(victim, 20)
	TEST_ASSERT_EQUAL(round(ash.body.getFireLoss(), DAMAGE_PRECISION), 6, "Пепел лечит ожоги однократно за перезарядку.")
	var/datum/heretic_innate/flesh/flesh = create_path(PATH_FLESH)
	flesh.blade_hit(victim, 100)
	TEST_ASSERT_EQUAL(round(flesh.reserve, DAMAGE_PRECISION), 6, "Плоть ограничивает запас от одного удара.")
	flesh.blade_hit(victim, 100)
	flesh.blade_hit(victim, 100)
	TEST_ASSERT_EQUAL(round(flesh.reserve, DAMAGE_PRECISION), 12, "У запаса плоти есть общий предел.")
	flesh.body.adjustBruteLoss(5)
	flesh.tick()
	TEST_ASSERT_EQUAL(round(flesh.body.getBruteLoss(), DAMAGE_PRECISION), 3, "Запас лечит ушибы.")
	TEST_ASSERT_EQUAL(round(flesh.reserve, DAMAGE_PRECISION), 10, "Запас расходуется по фактическому лечению.")
	var/datum/heretic_innate/blade/blade = create_path(PATH_BLADE)
	blade.body.adjustStaminaLoss(20)
	blade.blade_hit(victim, 20)
	TEST_ASSERT_EQUAL(blade.body.getStaminaLoss(), 20, "Первое попадание только начинает дуэль.")
	blade.blade_hit(victim, 20)
	blade.blade_hit(victim, 20)
	TEST_ASSERT_EQUAL(blade.body.getStaminaLoss(), 12, "Повторный удар восстанавливает выносливость с перезарядкой.")
	var/datum/heretic_innate/echo/echo = create_path(PATH_ECHO)
	var/mob/living/carbon/human/other = create_victim()
	echo.blade_hit(victim, 20)
	echo.blade_hit(victim, 20)
	TEST_ASSERT_EQUAL(round(victim.getBruteLoss(), DAMAGE_PRECISION), 0, "Эхо требует сменить цель.")
	echo.blade_hit(other, 20)
	TEST_ASSERT_EQUAL(round(other.getBruteLoss(), DAMAGE_PRECISION), 4, "Эхо ранит второго противника.")
	var/datum/heretic_innate/spirit/spirit = create_path(PATH_SPIRIT)
	spirit.body.adjustStaminaLoss(20)
	spirit.blade_hit(other, 20)
	TEST_ASSERT_EQUAL(spirit.body.getStaminaLoss(), 20, "Здоровая цель не даёт последний вздох.")
	other.adjustBruteLoss(60)
	spirit.blade_hit(other, 20)
	TEST_ASSERT_EQUAL(spirit.body.getStaminaLoss(), 12, "Раненый живой враг даёт последний вздох.")

/// Местность и обычные шаги питают черты, принудительное перемещение не подходит.
/datum/unit_test/heretic_innates/movement/Run()
	var/turf/origin = run_loc_floor_bottom_left
	var/turf/destination = get_step(origin, EAST)
	var/datum/heretic_innate/moon/moon = create_path(PATH_MOON)
	var/mob/living/carbon/human/victim = create_victim()
	moon.body.Move(destination, EAST)
	moon.body.Move(get_step(destination, NORTH), NORTH)
	moon.body.Move(get_step(origin, NORTH), WEST)
	TEST_ASSERT_EQUAL(length(moon.steps), 3, "Луна считает три разные клетки.")
	moon.blade_hit(victim, 20)
	TEST_ASSERT_EQUAL(victim.getStaminaLoss(), 8, "Три шага усиливают удар Луны.")
	moon.body.forceMove(destination)
	TEST_ASSERT_EQUAL(length(moon.steps), 0, "Телепорт сбрасывает шаги.")
	moon.body.forceMove(null)
	var/datum/heretic_innate/lock/lock = create_path(PATH_LOCK)
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock, origin)
	door.density = FALSE
	lock.body.Move(destination, EAST)
	TEST_ASSERT(lock.speed_until > world.time, "Проход через открытую дверь ускоряет Ключника.")
	TEST_ASSERT(lock.speed_timer, "Ускорение имеет отдельный таймер окончания.")
	lock.unbind()
	TEST_ASSERT_NULL(lock.speed_timer, "Снятие черты отменяет таймер.")
	var/datum/heretic_innate/rust/rust = create_path(PATH_RUST)
	rust.body.adjustBruteLoss(5)
	rust.tick()
	TEST_ASSERT_EQUAL(round(rust.body.getBruteLoss(), DAMAGE_PRECISION), 5, "Обычный пол не лечит.")
	var/turf/rust_floor = destination.ChangeTurf(/turf/open/floor/plating/rust)
	rust.body.forceMove(rust_floor)
	rust.next_tick = 0
	rust.tick()
	TEST_ASSERT_EQUAL(round(rust.body.getBruteLoss(), DAMAGE_PRECISION), 4, "Ржавый пол лечит без Ржавой поступи.")
	var/datum/heretic_innate/tide/tide = create_path(PATH_TIDE)
	tide.body.adjustStaminaLoss(20)
	var/turf/open/water_floor = get_step(origin, NORTH)
	water_floor.MakeSlippery(TURF_WET_WATER, min_wet_time = 10 SECONDS)
	tide.body.Move(water_floor, NORTH)
	TEST_ASSERT_EQUAL(tide.body.getStaminaLoss(), 14, "Шаг по воде восстанавливает выносливость.")
	tide.body.forceMove(null)
	var/datum/heretic_innate/cosmic/cosmic = create_path(PATH_COSMIC)
	var/datum/eldritch_knowledge/base_cosmic/stars = cosmic.knowledge_ref.resolve()
	TEST_ASSERT(stars.add_star(origin, cosmic.body), "Собственная звезда создаётся.")
	cosmic.body.adjustStaminaLoss(20)
	cosmic.body.Move(water_floor, NORTH)
	TEST_ASSERT_EQUAL(cosmic.body.getStaminaLoss(), 14, "Шаг возле собственной звезды восстанавливает выносливость.")

/// Ответные черты получают заряд только от фактических ранений.
/datum/unit_test/heretic_innates/damage/Run()
	var/datum/heretic_innate/glass/glass = create_path(PATH_GLASS)
	var/mob/living/carbon/human/victim = create_victim()
	glass.body.apply_damage(20, BRUTE, BODY_ZONE_CHEST, blocked = 100)
	TEST_ASSERT_EQUAL(glass.active_until, 0, "Полностью заблокированный урон не заряжает Стекло.")
	glass.body.adjustBruteLoss(4)
	TEST_ASSERT_EQUAL(glass.active_until, 0, "Недостаточный урон не заряжает ответ.")
	glass.body.adjustBruteLoss(4)
	TEST_ASSERT(glass.active_until > world.time, "Несколько обновлений здоровья учитывают весь полученный урон.")
	glass.blade_hit(victim, 20)
	glass.blade_hit(victim, 20)
	TEST_ASSERT_EQUAL(round(victim.getBruteLoss(), DAMAGE_PRECISION), 5, "Трещина расходуется одним ударом.")
	var/datum/heretic_innate/sand/sand = create_path(PATH_SAND)
	sand.body.adjustStaminaLoss(30)
	sand.body.adjustBruteLoss(10)
	sand.body.forceMove(get_step(run_loc_floor_bottom_left, EAST))
	TEST_ASSERT_EQUAL(sand.body.getStaminaLoss(), 30, "Принудительное перемещение не даёт бонус Песка.")
	sand.body.Move(get_step(get_step(run_loc_floor_bottom_left, EAST), NORTH), NORTH)
	TEST_ASSERT_EQUAL(sand.body.getStaminaLoss(), 18, "Обычный шаг после ранения восстанавливает выносливость.")
	var/datum/heretic_innate/dance/dance = create_path(PATH_DANCE)
	var/datum/eldritch_knowledge/base_dance/dance_knowledge = dance.knowledge_ref.resolve()
	dance.tick()
	TEST_ASSERT(!HAS_TRAIT(dance.body, TRAIT_SILENT_STEP), "Без Такта шаги Пляски слышны.")
	dance_knowledge.combat_resource = 1
	dance.next_tick = 0
	dance.tick()
	TEST_ASSERT(HAS_TRAIT(dance.body, TRAIT_SILENT_STEP), "С Тактом шаги Пляски беззвучны.")
	var/datum/heretic_innate/wax/wax = create_path(PATH_WAX)
	wax.body.adjustFireLoss(10)
	TEST_ASSERT_EQUAL(round(wax.reserve, DAMAGE_PRECISION), 10, "Ожоги сохраняются в памяти воска.")
	wax.body.adjustBruteLoss(10)
	wax.tick()
	TEST_ASSERT_EQUAL(round(wax.body.getBruteLoss(), DAMAGE_PRECISION), 8, "Воск расходует ожоги на лечение ушибов.")
	TEST_ASSERT_EQUAL(round(wax.body.getFireLoss(), DAMAGE_PRECISION), 10, "Полученные ожоги остаются.")
	wax.body.adjust_fire_stacks(3)
	wax.body.IgniteMob()
	wax.next_tick = 0
	wax.tick()
	TEST_ASSERT_EQUAL(round(wax.reserve, DAMAGE_PRECISION), 8, "Горящий воск не лечит.")

/// Перенос тела, смерть и снятие роли не оставляют черты и заряды прежнему телу.
/datum/unit_test/heretic_innates/lifecycle/Run()
	for(var/path_id in GLOB.heretic_paths)
		var/datum/heretic_innate/innate = create_path(path_id)
		var/mob/living/carbon/human/old_body = innate.body
		var/datum/antagonist/heretic/heretic = IS_HERETIC(old_body)
		innate.reserve = 10
		innate.active_until = world.time + 10 SECONDS
		innate.ready_at = world.time + 20 SECONDS
		var/mob/living/carbon/human/new_body = allocate(/mob/living/carbon/human, run_loc_floor_top_right)
		heretic.owner.transfer_to(new_body)
		TEST_ASSERT_EQUAL(innate.body, new_body, "[path_id]: черта следует за разумом.")
		TEST_ASSERT_EQUAL(round(innate.reserve, DAMAGE_PRECISION), 0, "[path_id]: запас прошлого тела исчезает.")
		TEST_ASSERT_EQUAL(innate.active_until, 0, "[path_id]: ответный удар не переносится.")
		TEST_ASSERT(innate.ready_at > world.time, "[path_id]: смена тела не сбрасывает перезарядку.")
		TEST_ASSERT_EQUAL(old_body.physiology.bleed_mod, 1, "Старое тело не сохраняет бонус крови.")
		TEST_ASSERT(!HAS_TRAIT(old_body, TRAIT_SILENT_STEP), "Старое тело не сохраняет бесшумность.")
		innate.reserve = 10
		new_body.death(FALSE)
		TEST_ASSERT_EQUAL(round(innate.reserve, DAMAGE_PRECISION), 0, "[path_id]: смерть сбрасывает запас.")
		heretic.clear_heretic()
		TEST_ASSERT_NULL(innate.body, "[path_id]: удаление роли отвязывает черту.")
		TEST_ASSERT_EQUAL(new_body.physiology.bleed_mod, 1, "Бонус крови снимается с нового тела.")
		TEST_ASSERT(!HAS_TRAIT(new_body, TRAIT_SILENT_STEP), "Бесшумность снимается с нового тела.")

/// Кровь соблюдает норму тела, а бонусы не срабатывают на союзниках и трупах.
/datum/unit_test/heretic_innates/blood_and_authority/Run()
	var/datum/heretic_innate/blood/blood = create_path(PATH_BLOOD)
	var/mob/living/carbon/human/user = blood.body
	var/mob/living/carbon/human/victim = create_victim()
	TEST_ASSERT_EQUAL(user.physiology.bleed_mod, 0.75, "Кровотечение слабее на четверть.")
	blood.bind(user)
	TEST_ASSERT_EQUAL(user.physiology.bleed_mod, 0.75, "Повторная привязка не складывает бонус.")
	user.blood_volume = BLOOD_VOLUME_NORMAL * user.blood_ratio - 1
	blood.blade_hit(victim, 20)
	TEST_ASSERT_EQUAL(user.blood_volume, BLOOD_VOLUME_NORMAL * user.blood_ratio, "Восстановление не превышает норму тела.")
	var/datum/heretic_innate/flesh/flesh = create_path(PATH_FLESH)
	flesh.blade_hit(user, 20)
	TEST_ASSERT_EQUAL(round(flesh.reserve, DAMAGE_PRECISION), 0, "Союзный еретик не даёт запас.")
	flesh.blade_hit(victim, 0)
	TEST_ASSERT_EQUAL(round(flesh.reserve, DAMAGE_PRECISION), 0, "Нулевой урон не даёт запас.")
	victim.death(FALSE)
	flesh.blade_hit(victim, 20)
	TEST_ASSERT_EQUAL(round(flesh.reserve, DAMAGE_PRECISION), 0, "Труп не даёт запас.")
	var/datum/eldritch_knowledge/knowledge = flesh.knowledge_ref.resolve()
	knowledge.on_lose(flesh.body)
	TEST_ASSERT_NULL(flesh.body, "Потеря знания снимает черту.")
	var/datum/heretic_innate/void/void = create_path(PATH_VOID)
	TEST_ASSERT(HAS_TRAIT(void.body, TRAIT_SILENT_STEP), "Пустота сразу получает бесшумные шаги.")
	var/mob/living/carbon/human/back = create_victim()
	back.forceMove(get_step(run_loc_floor_bottom_left, EAST))
	back.setDir(WEST)
	void.blade_hit(back, 20)
	TEST_ASSERT_EQUAL(back.getStaminaLoss(), 0, "Удар спереди не получает бонус Пустоты.")
	back.setDir(EAST)
	void.blade_hit(back, 20)
	TEST_ASSERT_EQUAL(back.getStaminaLoss(), 6, "Удар со спины получает бонус Пустоты.")

/// Настоящая цепочка атаки выдаёт запас только за урон клинком своего пути.
/datum/unit_test/heretic_innates/weapon/Run()
	var/datum/heretic_innate/flesh/flesh = create_path(PATH_FLESH)
	var/mob/living/carbon/human/user = flesh.body
	var/mob/living/carbon/human/victim = create_victim()
	victim.forceMove(get_step(user, EAST))
	var/obj/item/melee/sickly_blade/flesh/blade = allocate(/obj/item/melee/sickly_blade/flesh)
	user.put_in_hands(blade)
	victim.status_flags |= GODMODE
	blade.attack(victim, user)
	TEST_ASSERT_EQUAL(round(flesh.reserve, DAMAGE_PRECISION), 0, "Неуязвимый враг не даёт запас.")
	victim.status_flags &= ~GODMODE
	var/obj/item/melee/sickly_blade/rust/other_blade = allocate(/obj/item/melee/sickly_blade/rust)
	other_blade.attack(victim, user)
	TEST_ASSERT_EQUAL(round(flesh.reserve, DAMAGE_PRECISION), 0, "Клинок другого пути не питает черту.")
	blade.attack(victim, user)
	TEST_ASSERT(flesh.reserve > 0 && flesh.reserve <= 6, "Реальное попадание своим клинком даёт ограниченный запас.")
	var/reserve_before = flesh.reserve
	var/obj/item/nullrod/rod = allocate(/obj/item/nullrod)
	TEST_ASSERT(victim.put_in_hands(rod), "Цель держит нуллрод перед ударом.")
	TEST_ASSERT(!heretic_can_affect(user, victim, chargecost = 0), "Антимагия действует до попадания.")
	blade.attack(victim, user)
	TEST_ASSERT_EQUAL(round(flesh.reserve, DAMAGE_PRECISION), reserve_before, "Антимагия блокирует питание черты.")
