/// Хватка Пустоты гасит работающую лампу, повторный светильник в том же отделе не засчитывается.
/datum/unit_test/heretic_deed_void_lights/Run()
	var/datum/antagonist/heretic/heretic = allocate_deed_heretic(PATH_VOID)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_void/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_void)
	var/obj/machinery/light/first_lamp = allocate(/obj/machinery/light, get_step(user, EAST))
	first_lamp.status = LIGHT_OK
	first_lamp.on = TRUE
	TEST_ASSERT(knowledge.on_mansus_grasp(first_lamp, user, TRUE, null), "Хватка гасит работающую лампу.")
	TEST_ASSERT_EQUAL(first_lamp.status, LIGHT_BURNED, "Лампа перегорает.")
	TEST_ASSERT_EQUAL(heretic.deed.progress, 1, "Погашенная лампа засчитывается.")
	TEST_ASSERT(!knowledge.on_mansus_grasp(first_lamp, user, TRUE, null), "Перегоревшая лампа не принимает хватку.")
	COOLDOWN_RESET(heretic.deed, progress_cooldown)
	var/obj/machinery/light/second_lamp = allocate(/obj/machinery/light, get_step(user, WEST))
	second_lamp.status = LIGHT_OK
	second_lamp.on = TRUE
	TEST_ASSERT(knowledge.on_mansus_grasp(second_lamp, user, TRUE, null), "Вторая лампа тоже гаснет.")
	TEST_ASSERT_EQUAL(second_lamp.status, LIGHT_BURNED, "Вторая лампа перегорает.")
	TEST_ASSERT_EQUAL(heretic.deed.progress, 1, "Тот же отдел не засчитывается второй раз.")

/// Вызов засчитывает нового человека в дело Клинка один раз, принятый вызов - за два шага со следом там, где его приняли, отказ без игрока в теле - ни за один.
/datum/unit_test/heretic_deed_blade_challenges/Run()
	allocated += new /datum/heretic_test_station_level(run_loc_floor_bottom_left.z)
	var/datum/antagonist/heretic/heretic = allocate_deed_heretic(PATH_BLADE)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_blade/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_blade)
	var/mob/living/carbon/human/first = blade_test_crew(get_step(get_step(user, EAST), EAST))
	var/mob/living/carbon/human/second = blade_test_crew(get_step(get_step(user, NORTH), NORTH))
	knowledge.combat_resource = 0
	knowledge.open_challenge(user, first)
	TEST_ASSERT(knowledge.decline_duel(first, "отказ"), "Отказ закрывает вызов.")
	TEST_ASSERT_EQUAL(heretic.deed.progress, 1, "Вызов нового человека засчитан.")
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 1, "Шаг дела даёт Темп.")
	TEST_ASSERT_NOTNULL(locate(/obj/effect/decal/cleanable/heretic_trace) in get_turf(first), "Вызов оставляет след у вызванного.")
	var/reason = knowledge.challenge_block_reason(user, second)
	TEST_ASSERT(findtext(reason, "Слишком быстро"), "Пауза дела не даёт вызвать нового человека: [reason]")
	COOLDOWN_RESET(heretic.deed, progress_cooldown)
	knowledge.challenge_repeat.Cut()
	knowledge.open_challenge(user, first)
	knowledge.decline_duel(first, "отказ")
	TEST_ASSERT_EQUAL(heretic.deed.progress, 1, "Тот же человек второй раз не засчитывается.")
	knowledge.open_challenge(user, second)
	var/turf/accepted_at = get_turf(second)
	TEST_ASSERT(knowledge.accept_duel(second), "Второй принимает вызов.")
	TEST_ASSERT(heretic.pocket?.contains(second), "Принявший вызов ушёл в изнанку.")
	TEST_ASSERT_EQUAL(heretic.deed.tier, 1, "Принятый вызов засчитан за два шага: первая ступень закрыта.")
	TEST_ASSERT_EQUAL(heretic.deed.progress, 1, "Второй шаг принятого вызова лёг на новую ступень.")
	TEST_ASSERT_NOTNULL(locate(/obj/effect/decal/cleanable/heretic_trace) in accepted_at, "Принятый вызов оставляет след дела там, где его приняли, а не в изнанке.")
	knowledge.active_duel.expire()
	COOLDOWN_RESET(heretic.deed, progress_cooldown)
	COOLDOWN_RESET(heretic.pocket, reopen_cooldown)
	var/mob/living/carbon/human/fallen = blade_test_crew(locate(user.x + 3, user.y + 1, user.z))
	TEST_ASSERT_NULL(knowledge.challenge_block_reason(user, fallen), "Изнанка снова готова: мешать дуэли может только поза соперника.")
	fallen.Knockdown(5 SECONDS)
	knowledge.open_challenge(user, fallen)
	TEST_ASSERT(!knowledge.accept_duel(fallen), "С лежащим соперником дуэль не начинается.")
	TEST_ASSERT_NULL(knowledge.active_duel, "Дуэль не началась.")
	TEST_ASSERT(!heretic.pocket.active, "Изнанка для лежащего соперника не открылась.")
	TEST_ASSERT_EQUAL(heretic.deed.progress, 1, "Несостоявшаяся дуэль не засчитывается в дело.")
	TEST_ASSERT_NULL(knowledge.challenge_repeat[knowledge.challenge_key(fallen)], "Несостоявшаяся дуэль не закрывает повторный вызов.")
	COOLDOWN_RESET(heretic.pocket, reopen_cooldown)
	var/mob/living/carbon/human/third = blade_test_crew(get_step(user, NORTHEAST))
	TEST_ASSERT(knowledge.challenge(user, third), "Вызов без игрока в теле брошен.")
	TEST_ASSERT_NULL(knowledge.challenged_ref, "Без игрока в теле вызов сразу считается отказом.")
	TEST_ASSERT_EQUAL(heretic.deed.progress, 1, "Отказ без игрока в теле не засчитывается.")

/// Двойник на посту засчитывает отдел станции, когда его видит член экипажа, каждый отдел один раз; вне станции, вне отдела поста, хозяин, слепой и другой еретик не в счёт.
/datum/unit_test/heretic_deed_moon_post/Run()
	var/datum/antagonist/heretic/heretic = allocate_deed_heretic(PATH_MOON)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_moon/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_moon)
	var/turf/spot = locate(user.x + 3, user.y + 2, user.z)
	TEST_ASSERT(knowledge.place_post(user, spot), "Двойник встаёт на пост.")
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/post/post = knowledge.post_double
	var/mob/living/carbon/human/crew = allocate(/mob/living/carbon/human, get_step(spot, NORTH))
	crew.mind_initialize()
	TEST_ASSERT(!post.witnessed_by(crew), "Вне станции двойник в дело не идёт.")
	allocated += new /datum/heretic_test_station_level(run_loc_floor_bottom_left.z)
	ADD_TRAIT(crew, TRAIT_BLIND, TRAIT_SOURCE_UNIT_TESTS)
	TEST_ASSERT(!post.witnessed_by(crew), "Слепой не видит двойника.")
	REMOVE_TRAIT(crew, TRAIT_BLIND, TRAIT_SOURCE_UNIT_TESTS)
	TEST_ASSERT(!post.witnessed_by(user), "Хозяин своему двойнику не свидетель.")
	var/datum/antagonist/heretic/ally = allocate_heretic(get_step(spot, SOUTH))
	TEST_ASSERT(!post.witnessed_by(ally.owner.current), "Другой еретик не свидетель.")
	TEST_ASSERT_EQUAL(heretic.deed.progress, 0, "Без свидетеля отдел не засчитан.")
	TEST_ASSERT(post.witnessed_by(crew), "Член экипажа увидел двойника.")
	TEST_ASSERT_EQUAL(heretic.deed.progress, 1, "Отдел засчитан в дело.")
	COOLDOWN_RESET(heretic.deed, progress_cooldown)
	var/mob/living/carbon/human/second = allocate(/mob/living/carbon/human, get_step(spot, EAST))
	second.mind_initialize()
	TEST_ASSERT(!post.witnessed_by(second), "Тот же отдел второй раз не засчитывается.")
	heretic_test_area(spot, /area/unit_test_moon_noteleport)
	TEST_ASSERT(post.witnessed_by(second), "Двойника увидели в другом отделе.")
	TEST_ASSERT_EQUAL(heretic.deed.tier, 1, "Два отдела закрывают первую ступень.")
	COOLDOWN_RESET(heretic.deed, progress_cooldown)
	var/turf/away = get_step(spot, WEST)
	heretic_test_area(away, /area/unit_test_cosmic_deck)
	post.forceMove(away)
	TEST_ASSERT(!post.witnessed_by(second), "Двойник, утащенный с поста в другой отдел, не засчитывается.")
	TEST_ASSERT_EQUAL(heretic.deed.progress, 0, "Утащенный двойник не двигает дело.")
	post.anchor_turf = away
	TEST_ASSERT(post.witnessed_by(second), "Двойник на новом посту засчитывается.")
