/// Хватка и настоящее попадание клинком дают ограниченный запас; повторный удар учитывает задержку сбора.
/datum/unit_test/heretic_tide_pressure_cycle/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/tide_grasp)
	heretic.gain_knowledge(/datum/eldritch_knowledge/tide_mark)
	var/mob/living/user = heretic.owner.current
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(user, EAST))
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/tide_grasp/grasp = heretic.get_knowledge(/datum/eldritch_knowledge/tide_grasp)
	var/datum/eldritch_knowledge/tide_mark/mark_knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/tide_mark)
	var/obj/item/melee/sickly_blade/tide/blade = allocate(/obj/item/melee/sickly_blade/tide)
	tide.combat_resource = 0
	TEST_ASSERT(grasp.on_mansus_grasp(victim, user, TRUE, null), "Хватка по противнику должна набрать давление.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 2, "Одна хватка даёт две единицы давления.")
	TEST_ASSERT(victim.has_status_effect(/datum/status_effect/heretic_drenched), "Хватка оставляет воду Пучины.")
	TEST_ASSERT(mark_knowledge.on_mansus_grasp(victim, user, TRUE, null), "Хватка должна оставить метку.")
	blade.afterattack(victim, user, TRUE, null)
	TEST_ASSERT_EQUAL(tide.combat_resource, 2, "Один afterattack без ранения не собирает давление.")
	user.a_intent = INTENT_HARM
	blade.attack(victim, user)
	TEST_ASSERT(!victim.has_status_effect(/datum/status_effect/eldritch/tide), "Настоящее попадание гарпуном активирует метку.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 4, "Детонация и первое попадание дают по одной единице.")
	TEST_ASSERT(tide.spend_combat_resource(2), "Накопленное давление расходуется.")
	blade.attack(victim, user)
	TEST_ASSERT_EQUAL(tide.combat_resource, 2, "Второе попадание в тот же момент не обходит задержку сбора.")
	tide.gain_combat_resource(100)
	TEST_ASSERT_EQUAL(tide.combat_resource, 4, "Давление не превышает вместимость.")
	TEST_ASSERT(!tide.spend_combat_resource(5), "Нельзя потратить больше доступного запаса.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 4, "Неудачная трата сохраняет запас.")

/// Волна сдвигает врага и обходит союзников, а отказ из-за нехватки давления не расходует антимагию.
/datum/unit_test/heretic_tide_release_protection/Run()
	var/turf/center = get_step(get_step(get_step(get_step(run_loc_floor_bottom_left, EAST), EAST), NORTH), NORTH)
	var/datum/antagonist/heretic/heretic = allocate_heretic(center)
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(center, EAST))
	var/datum/antagonist/heretic/ally = allocate_heretic(get_step(center, NORTH))
	var/mob/living/protected = allocate(/mob/living/carbon/human, get_step(center, WEST))
	var/datum/component/anti_magic/protection = protected.AddComponent(/datum/component/anti_magic, TRUE, FALSE, FALSE, null, 5)
	tide.combat_resource = 1
	TEST_ASSERT(!tide.release(user), "Без двух единиц волна не применяется.")
	TEST_ASSERT_EQUAL(protection.charges, 5, "Недостаток давления не расходует антимагию.")
	tide.combat_resource = 4
	TEST_ASSERT(tide.release(user), "Подготовленная волна должна сработать.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 2, "Сброс тратит ровно две единицы.")
	TEST_ASSERT(abs(victim.getBruteLoss() - 18) < 0.001, "Волна наносит восемнадцать ушибов.")
	TEST_ASSERT(abs(victim.getStaminaLoss() - 24) < 0.001, "Волна наносит двадцать четыре урона выносливости.")
	TEST_ASSERT_EQUAL(get_dist(user, victim), 3, "Волна смывает соседнего врага на две клетки.")
	TEST_ASSERT(tide.on_wet_floor(victim), "Смытый враг лежит в луже: Захлебнуться берёт его сразу.")
	TEST_ASSERT(victim.IsKnockdown(), "Волна сбивает противника с ног.")
	TEST_ASSERT_EQUAL(round(victim.AmountKnockdown(), 0.01), 2.5 SECONDS, "Сброс оставляет время на продолжение атаки или отход.")
	TEST_ASSERT(victim.has_movespeed_modifier(/datum/movespeed_modifier/heretic_drenched), "Волна замедляет намокшую цель.")
	TEST_ASSERT_EQUAL(ally.owner.current.getBruteLoss(), 0, "Волна не ранит другого еретика.")
	TEST_ASSERT_EQUAL(user.getBruteLoss(), 0, "Волна не ранит создателя.")
	TEST_ASSERT_EQUAL(protected.getBruteLoss(), 0, "Антимагия блокирует весь урон волны.")
	TEST_ASSERT(!protected.has_movespeed_modifier(/datum/movespeed_modifier/heretic_drenched), "Антимагия защищает и от замедления.")
	TEST_ASSERT_EQUAL(protection.charges, 4, "Вся волна расходует один заряд защиты на цель.")

/// Стол между еретиком и клеткой не закрывает линию магии Пучины, а плотная машина закрывает, и отказ называет преграду.
/datum/unit_test/heretic_tide_line_table/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_well)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/spell/tide_well/spell_knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/spell/tide_well)
	var/obj/effect/proc_holder/spell/pointed/heretic_tide/well/spell = spell_knowledge.granted_spell
	var/turf/target = locate(user.x + 4, user.y, user.z)
	allocate(/obj/structure/table, locate(user.x + 2, user.y, user.z))
	TEST_ASSERT(spell.can_target(target, user, TRUE), "Стол не закрывает линию.")
	var/obj/machinery/hydroponics/machine = allocate(/obj/machinery/hydroponics, locate(user.x + 1, user.y, user.z))
	TEST_ASSERT(machine.density, "Лоток гидропоники плотный.")
	TEST_ASSERT(!spell.can_target(target, user, TRUE), "Плотная машина закрывает линию.")
	TEST_ASSERT(findtext(spell.heretic_failure_reason, "преграда"), "Отказ называет преграду: [spell.heretic_failure_reason]")

/// Водоворот разрушается жезлом, заменяется новым и прекращает действовать вдали от владельца.
/datum/unit_test/heretic_tide_well_lifecycle/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_well)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/turf/center = get_step(user, EAST)
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(get_step(center, EAST), EAST))
	ADD_TRAIT(victim, TRAIT_NOSLIPWATER, REF(src))
	tide.combat_resource = 4
	TEST_ASSERT(tide.create_well(user, center), "На свободном полу создаётся водоворот.")
	var/obj/structure/heretic_tide_well/first = tide.active_well
	TEST_ASSERT_EQUAL(first.obj_integrity, 60, "У водоворота конечная прочность.")
	TEST_ASSERT(abs(victim.getBruteLoss() - 12) < 0.001, "Создание воронки сразу наносит урон.")
	TEST_ASSERT(abs(victim.getStaminaLoss() - 18) < 0.001, "Первое течение изматывает противника.")
	TEST_ASSERT_EQUAL(get_dist(first, victim), 1, "Создание воронки сразу притягивает цель.")
	TEST_ASSERT_EQUAL(round(victim.AmountKnockdown(), 0.01), 1.5 SECONDS, "Первый удар воронки даёт время воспользоваться притяжением.")
	victim.SetKnockdown(0)
	TEST_ASSERT(first.pulse(), "Водоворот действует в присутствии владельца.")
	TEST_ASSERT_EQUAL(round(victim.AmountKnockdown(), 0.01), 0.6 SECONDS, "Повторный пульс оставляет возможность выбраться между ударами.")
	TEST_ASSERT(abs(victim.getBruteLoss() - 24) < 0.001, "Ядро воронки наносит ещё двенадцать ушибов.")
	TEST_ASSERT(abs(victim.getStaminaLoss() - 30) < 0.001, "Ядро воронки дополнительно изматывает цель.")
	TEST_ASSERT_EQUAL(get_dist(first, victim), 0, "Пульс затягивает цель в саму воронку.")
	TEST_ASSERT(tide.create_well(user, center), "Новый водоворот заменяет старый.")
	TEST_ASSERT(QDELETED(first), "Старая воронка удаляется при создании новой.")
	var/obj/structure/heretic_tide_well/second = tide.active_well
	TEST_ASSERT(!tide.create_well(user, center), "Без давления нельзя заменить воронку.")
	TEST_ASSERT_EQUAL(tide.active_well, second, "Неудачное создание сохраняет действующую воронку.")
	var/datum/component/anti_magic/protection = victim.AddComponent(/datum/component/anti_magic, TRUE, FALSE, FALSE, null, 5)
	var/stamina_before = victim.getStaminaLoss()
	second.pulse()
	TEST_ASSERT_EQUAL(protection.charges, 4, "Пульс расходует один заряд антимагии.")
	TEST_ASSERT_EQUAL(victim.getStaminaLoss(), stamina_before, "Защищённый противник не получает урон пульса.")
	var/turf/original_turf = get_turf(user)
	user.forceMove(locate(original_turf.x + 10, original_turf.y, original_turf.z))
	TEST_ASSERT(!second.pulse(), "Водоворот не действует вдали от своего владельца.")
	TEST_ASSERT_EQUAL(protection.charges, 4, "Неактивная воронка не расходует защиту.")
	user.forceMove(original_turf)
	var/obj/item/nullrod/rod = allocate(/obj/item/nullrod)
	second.attackby(rod, victim)
	TEST_ASSERT(QDELETED(second), "Нулевой жезл уничтожает водоворот.")
	TEST_ASSERT_NULL(tide.active_well, "Разрушенная воронка освобождает ссылку владельца.")

/// Обрушение расходует запас один раз и не расширяется на клетки, открытые после предупреждения.
/datum/unit_test/heretic_tide_deluge_telegraph/Run()
	var/turf/center = get_step(get_step(run_loc_floor_bottom_left, EAST), NORTH)
	var/datum/antagonist/heretic/heretic = allocate_heretic(center)
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_deluge)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/turf/hidden = get_step(center, EAST)
	var/obj/blocker = allocate(/obj, hidden)
	blocker.density = TRUE
	var/list/warned = tide.deluge_turfs(user, center)
	TEST_ASSERT(center in warned, "Центр входит в предупреждённую область.")
	TEST_ASSERT(!(hidden in warned), "Клетка за преградой не получает предупреждение.")
	qdel(blocker)
	var/mob/living/unwarned = allocate(/mob/living/carbon/human, hidden)
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(center, NORTH))
	var/mob/living/protected = allocate(/mob/living/carbon/human, get_step(center, WEST))
	var/datum/component/anti_magic/protection = protected.AddComponent(/datum/component/anti_magic, TRUE, FALSE, FALSE, null, 5)
	tide.combat_resource = 4
	TEST_ASSERT(!tide.deluge(user, center, list(), tide.tide_generation), "Без предупреждённых клеток обрушения нет.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 4, "Отказ сохраняет давление.")
	TEST_ASSERT(tide.deluge(user, center, warned, tide.tide_generation), "Подготовленное обрушение должно завершиться.")
	TEST_ASSERT(abs(victim.getBruteLoss() - 44) < 0.001, "Четыре единицы дают сорок четыре ушиба.")
	TEST_ASSERT(abs(victim.getStaminaLoss() - 32) < 0.001, "Четыре единицы дают тридцать два урона выносливости.")
	TEST_ASSERT(victim.IsKnockdown(), "Обрушение сбивает противника.")
	TEST_ASSERT_EQUAL(unwarned.getBruteLoss(), 0, "Открытие прохода не добавляет непредупреждённую цель.")
	TEST_ASSERT_EQUAL(protected.getBruteLoss(), 0, "Антимагия защищает от обрушения.")
	TEST_ASSERT_EQUAL(protection.charges, 4, "Обрушение расходует один заряд защиты.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 0, "Обрушение расходует весь исходный запас.")
	TEST_ASSERT(!tide.deluge(user, center, warned, tide.tide_generation), "Без нового запаса повторить удар нельзя.")
	var/original_generation = tide.tide_generation
	tide.on_death(user)
	tide.combat_resource = 4
	TEST_ASSERT(!tide.deluge(user, center, warned, original_generation), "Даже после быстрого оживления старое предупреждение теряет силу.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 4, "Отменённая смертью подготовка сохраняет новый запас.")
	original_generation = tide.tide_generation
	tide.on_body_lose(user)
	tide.on_body_gain(user)
	TEST_ASSERT(!tide.deluge(user, center, warned, original_generation), "Уход из тела и возврат не восстанавливают старую подготовку.")

/// Реальная подготовка допускает шаг в пределах двух клеток и отменяет дальний отход.
/datum/unit_test/heretic_tide_deluge_movement/Run()
	var/turf/origin = get_step(get_step(run_loc_floor_bottom_left, NORTHEAST), NORTHEAST)
	var/datum/antagonist/heretic/heretic = allocate_heretic(origin)
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_deluge)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/obj/effect/proc_holder/spell/pointed/heretic_tide/deluge/spell = allocate(/obj/effect/proc_holder/spell/pointed/heretic_tide/deluge)
	var/turf/center = get_step(get_step(origin, EAST), EAST)
	var/mob/living/victim = allocate(/mob/living/carbon/human, center)
	var/turf/nearby = get_step(get_step(origin, NORTH), NORTH)
	tide.combat_resource = 4
	addtimer(CALLBACK(user, TYPE_PROC_REF(/atom/movable, forceMove), nearby), 0.2 SECONDS)
	spell.cast(list(center), user)
	TEST_ASSERT_EQUAL(user.loc, nearby, "Игрок действительно сместился во время подготовки.")
	TEST_ASSERT(abs(victim.getBruteLoss() - 44) <= DAMAGE_PRECISION, "Две клетки движения сохраняют полный удар по прежней области.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 0, "Успешный удар расходует давление.")
	user.forceMove(origin)
	tide.combat_resource = 4
	var/turf/distant = get_step(nearby, NORTH)
	addtimer(CALLBACK(user, TYPE_PROC_REF(/atom/movable, forceMove), distant), 0.2 SECONDS)
	spell.cast(list(center), user)
	TEST_ASSERT_EQUAL(user.loc, distant, "Игрок вышел за допустимые две клетки.")
	TEST_ASSERT(abs(victim.getBruteLoss() - 44) <= DAMAGE_PRECISION, "Прерванный удар не наносит дополнительного урона.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 4, "Прерывание сохраняет запас.")
	user.forceMove(origin)
	var/obj/blocker = allocate(/obj, get_step(origin, EAST))
	blocker.density = TRUE
	TEST_ASSERT(!tide.can_prepare_deluge(user, origin, center, tide.tide_generation), "Преграда разрывает подготовку даже в пределах шага.")
	qdel(blocker)
	user.Paralyze(1 SECONDS)
	TEST_ASSERT(!tide.can_prepare_deluge(user, origin, center, tide.tide_generation), "Оглушение по-прежнему прерывает подготовку.")

/// Обрушение оставляет море радиусом 4: оно мочит врагов, ускоряет героя, копит давление и уходит со смертью.
/datum/unit_test/heretic_tide_deluge_sea/Run()
	var/turf/center = run_loc_floor_bottom_left
	var/datum/antagonist/heretic/heretic = allocate_heretic(center)
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_deluge)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/turf/shore = locate(center.x + 4, center.y, center.z)
	var/turf/beyond = locate(center.x + 5, center.y, center.z)
	var/turf/glazed = locate(center.x, center.y + 3, center.z)
	var/turf/behind_glass = locate(center.x, center.y + 4, center.z)
	allocate(/obj/structure/window/fulltile, glazed)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, locate(center.x + 3, center.y + 3, center.z))
	var/mob/living/carbon/human/walker = allocate(/mob/living/carbon/human, beyond)
	tide.combat_resource = 2
	TEST_ASSERT(tide.deluge(user, center, tide.deluge_turfs(user, center), tide.tide_generation), "Обрушение должно состояться.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(shore), 1, "Море доходит до четырёх клеток.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(beyond), 0, "Пятая клетка остаётся сухой.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(behind_glass), 0, "Окно не пропускает море.")
	TEST_ASSERT_NULL(shore.GetComponent(/datum/component/wet_floor), "Море за зоной удара не делает пол скользким.")
	var/obj/effect/heretic_tide_puddle/sea/puddle = locate() in shore
	TEST_ASSERT(puddle.expires_at == world.time + 15 SECONDS, "Море держится 15 секунд.")
	TEST_ASSERT(bystander.has_status_effect(/datum/status_effect/heretic_drenched), "Враг, стоявший в разлившейся воде, намокает.")
	walker.forceMove(shore)
	TEST_ASSERT(walker.has_status_effect(/datum/status_effect/heretic_drenched), "Вошедший в море намокает.")
	TEST_ASSERT(user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_sea), "В своём море герой быстрее.")
	user.forceMove(beyond)
	TEST_ASSERT(!user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_sea), "На сухом полу ускорение пропадает.")
	user.forceMove(center)
	COOLDOWN_START(tide, ascended_pressure, 12 SECONDS)
	tide.on_life(user)
	TEST_ASSERT(COOLDOWN_TIMELEFT(tide, ascended_pressure) < 4 SECONDS + 1, "В море давление восстанавливается раз в 4 секунды.")
	COOLDOWN_RESET(tide, ascended_pressure)
	tide.on_life(user)
	TEST_ASSERT_EQUAL(tide.combat_resource, 1, "Море возвращает давление.")
	TEST_ASSERT(COOLDOWN_TIMELEFT(tide, ascended_pressure) < 4 SECONDS + 1, "Следующая единица тоже через 4 секунды.")
	tide.on_death(user)
	TEST_ASSERT_EQUAL(tide_flood_puddles(shore), 0, "Смерть осушает море.")
	TEST_ASSERT_EQUAL(length(tide.sea), 0, "Знание не держит ссылок на ушедшую воду.")
	TEST_ASSERT(!user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_sea), "Смерть снимает ускорение моря.")

/// Замена воды передаёт её новому источнику, а удаление роли снимает только собственные эффекты.
/datum/unit_test/heretic_tide_drenched_cleanup/Run()
	var/datum/antagonist/heretic/first = allocate_heretic()
	var/datum/antagonist/heretic/second = allocate_heretic(get_step(run_loc_floor_bottom_left, NORTH))
	first.selected_path = PATH_TIDE
	second.selected_path = PATH_TIDE
	first.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	second.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/base_tide/first_tide = first.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/base_tide/second_tide = second.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(run_loc_floor_bottom_left, EAST))
	first_tide.soak(victim)
	victim.apply_status_effect(/datum/status_effect/eldritch/tide, first_tide)
	TEST_ASSERT_EQUAL(length(first_tide.marks), 1, "Знание отслеживает собственную метку.")
	TEST_ASSERT_EQUAL(length(first_tide.drenched), 1, "Знание отслеживает собственную воду.")
	second_tide.soak(victim)
	TEST_ASSERT_EQUAL(length(first_tide.drenched), 0, "Замена снимает эффект из списка прежнего владельца.")
	TEST_ASSERT_EQUAL(length(second_tide.drenched), 1, "Новая вода принадлежит второму еретику.")
	TEST_ASSERT_EQUAL(length(victim.has_status_effect_list(/datum/status_effect/heretic_drenched)), 1, "Вода не складывается на одной цели.")
	TEST_ASSERT(victim.has_movespeed_modifier(/datum/movespeed_modifier/heretic_drenched), "Замена воды сохраняет замедление нового владельца.")
	qdel(first)
	TEST_ASSERT(victim.has_status_effect(/datum/status_effect/heretic_drenched), "Удаление первой роли не снимает чужую воду.")
	TEST_ASSERT(!victim.has_status_effect(/datum/status_effect/eldritch/tide), "Удаление первой роли снимает её собственную метку.")
	victim.remove_status_effect(/datum/status_effect/heretic_drenched)
	TEST_ASSERT(!victim.has_movespeed_modifier(/datum/movespeed_modifier/heretic_drenched), "Окончание намокания снимает замедление.")
	TEST_ASSERT_EQUAL(length(second_tide.drenched), 0, "Обычное снятие статуса освобождает список владельца.")
	second_tide.soak(victim)
	victim.apply_status_effect(/datum/status_effect/eldritch/tide, second_tide)
	qdel(second)
	TEST_ASSERT(!victim.has_status_effect(/datum/status_effect/heretic_drenched), "Удаление роли снимает оставшуюся воду.")
	TEST_ASSERT(!victim.has_movespeed_modifier(/datum/movespeed_modifier/heretic_drenched), "Удаление владельца не оставляет замедление на цели.")
	TEST_ASSERT(!victim.has_status_effect(/datum/status_effect/eldritch/tide), "Удаление роли снимает оставшуюся метку.")

/// Колокол принадлежит создателю, переключает направление волны и допускает замену только после уничтожения.
/datum/unit_test/heretic_tide_bell/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/tide_bell)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/tide_bell/recipe = heretic.get_knowledge(/datum/eldritch_knowledge/tide_bell)
	TEST_ASSERT(recipe.on_finished_recipe(user, list(), get_turf(user)), "Обряд создаёт колокол.")
	var/obj/item/heretic_path_relic/tide_bell/bell = recipe.new_path_relic_ref.resolve()
	allocated += bell
	TEST_ASSERT(!recipe.on_finished_recipe(user, list(), get_turf(user)), "Второй колокол нельзя создать, пока первый существует.")
	TEST_ASSERT(!bell.ring(user), "Колокол на полу не подчиняется мысленному приказу.")
	user.put_in_hands(bell)
	TEST_ASSERT(bell.ring(user), "Создатель может позвонить колоколом в руке.")
	TEST_ASSERT(tide.inward_tide, "Звон переключает отталкивание на притяжение.")
	TEST_ASSERT(!bell.ring(user), "Повторный звон ограничен перезарядкой.")
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(get_step(user, EAST), EAST))
	tide.combat_resource = 2
	TEST_ASSERT(tide.release(user), "Переключённая волна расходует обычный запас.")
	TEST_ASSERT_EQUAL(get_dist(user, victim), 1, "Прилив действительно притягивает противника на клетку.")
	var/datum/antagonist/heretic/stranger = allocate_heretic(get_step(user, NORTH))
	user.dropItemToGround(bell, TRUE)
	stranger.owner.current.put_in_hands(bell)
	COOLDOWN_RESET(bell, relic_cooldown)
	TEST_ASSERT(!bell.ring(stranger.owner.current), "Другой еретик не может настроить чужой колокол.")
	qdel(bell)
	TEST_ASSERT(recipe.new_path_relic_available(), "Разбитый колокол освобождает рецепт.")

/// Колокол обращает существующую воронку наружу без дополнительного пульса и падения.
/datum/unit_test/heretic_tide_outward_well/Run()
	var/turf/center = get_step(get_step(run_loc_floor_bottom_left, NORTHEAST), NORTHEAST)
	var/datum/antagonist/heretic/heretic = allocate_heretic(get_step(center, WEST))
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/tide_bell)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_well)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/tide_bell/recipe = heretic.get_knowledge(/datum/eldritch_knowledge/tide_bell)
	TEST_ASSERT(recipe.on_finished_recipe(user, list(), get_turf(user)), "Создаётся личный колокол.")
	var/obj/item/heretic_path_relic/tide_bell/bell = recipe.new_path_relic_ref.resolve()
	allocated += bell
	user.put_in_hands(bell)
	TEST_ASSERT(tide.create_well(user, center), "Создаётся воронка.")
	var/obj/structure/heretic_tide_well/well = tide.active_well
	var/expiry_before = well.expires_at
	var/pulse_before = well.well_pulse
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(center, EAST))
	TEST_ASSERT(bell.afterattack(well, user, FALSE), "Колокол выбирает именно существующую воронку.")
	TEST_ASSERT(well.outward, "Воронка переходит в режим отвода.")
	TEST_ASSERT_EQUAL(well.expires_at, expiry_before, "Переключение сохраняет срок жизни.")
	TEST_ASSERT_EQUAL(well.well_pulse, pulse_before, "Переключение сохраняет расписание пульсов.")
	TEST_ASSERT_EQUAL(victim.getBruteLoss(), 0, "Переключение не создаёт мгновенный удар.")
	TEST_ASSERT(well.pulse(), "Следующий пульс использует наружное течение.")
	TEST_ASSERT_EQUAL(get_dist(well, victim), 2, "Наружный поток отодвигает на одну клетку.")
	TEST_ASSERT(abs(victim.getBruteLoss() - 6) <= DAMAGE_PRECISION, "Наружный пульс использует слабый урон края.")
	TEST_ASSERT(!victim.IsKnockdown(), "Наружный пульс не сбивает с ног.")
	var/obj/blocker = allocate(/obj, get_step(victim, EAST))
	blocker.density = TRUE
	TEST_ASSERT(well.pulse(), "Преграда останавливает наружное перемещение.")
	TEST_ASSERT(abs(victim.getBruteLoss() - 12) <= DAMAGE_PRECISION, "Преграда не добавляет столкновительный урон.")
	TEST_ASSERT(!victim.IsKnockdown(), "Упор в стену не превращает отвод в повторяющееся падение.")
	TEST_ASSERT(!bell.redirect_well(user, well), "Повторное переключение ограничено перезарядкой колокола.")
	COOLDOWN_RESET(bell, relic_cooldown)
	TEST_ASSERT(bell.redirect_well(user, well) && !well.outward, "Колокол возвращает обычное притяжение.")

/// Пассивка расширяет вместимость без бесплатного ресурса; смерть убирает воронку, воду и запас.
/datum/unit_test/heretic_tide_capacity_and_death/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/tide_depth)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_well)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/tide_depth/depth = heretic.get_knowledge(/datum/eldritch_knowledge/tide_depth)
	TEST_ASSERT_EQUAL(tide.combat_resource_max, 5, "Первая ступень пассивки расширяет вместимость до пяти.")
	TEST_ASSERT_EQUAL(tide.combat_resource, initial(tide.combat_resource), "Изучение не заполняет дополнительную вместимость.")
	depth.passive_level = 3
	depth.on_passive_upgrade(user)
	TEST_ASSERT_EQUAL(tide.combat_resource_max, 7, "Третья ступень пассивки расширяет вместимость до семи.")
	TEST_ASSERT_EQUAL(tide.combat_resource, initial(tide.combat_resource), "Улучшение также не создаёт давление.")
	heretic.gain_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	var/datum/eldritch_knowledge/final_eldritch/tide_final/finale = heretic.get_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	heretic.ascended = TRUE
	finale.finished = TRUE
	finale.on_body_gain(user)
	TEST_ASSERT_EQUAL(tide.combat_resource_max, 8, "После вознесения вмещаются восемь единиц.")
	tide.combat_resource = 1
	TEST_ASSERT(!tide.release(user), "Даже вознесённый обычный сброс требует две единицы.")
	tide.combat_resource = 4
	TEST_ASSERT(tide.create_well(user, get_turf(user)), "Перед смертью существует воронка.")
	var/obj/structure/heretic_tide_well/well = tide.active_well
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(user, EAST))
	tide.soak(victim)
	victim.apply_status_effect(/datum/status_effect/eldritch/tide, tide)
	user.stat = DEAD
	heretic.handle_death(user)
	TEST_ASSERT(QDELETED(well), "Смерть немедленно убирает водоворот.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 0, "Смерть сбрасывает накопленное давление.")
	TEST_ASSERT(!victim.has_status_effect(/datum/status_effect/heretic_drenched), "Смерть освобождает противника от воды.")
	TEST_ASSERT(!victim.has_status_effect(/datum/status_effect/eldritch/tide), "Смерть убирает метку с чужого тела.")
	TEST_ASSERT(!tide.release(user, ascended_wave = TRUE), "Мёртвый владелец не выпускает бесплатную волну.")
	TEST_ASSERT_EQUAL(tide.combat_resource_max, 7, "Смерть возвращает вместимость пассивки.")
	var/obj/effect/proc_holder/spell/power = tide.combat_power
	tide.on_body_lose(user)
	TEST_ASSERT(QDELETED(power), "Отвязка тела удаляет исходную способность.")
	TEST_ASSERT_NULL(tide.tide_body, "Отвязка освобождает ссылку на старое тело.")

/// Снос в преграду наносит один удар и не проталкивает противника сквозь неё.
/datum/unit_test/heretic_tide_wave_collision/Run()
	var/turf/center = get_step(get_step(run_loc_floor_bottom_left, EAST), NORTH)
	var/datum/antagonist/heretic/heretic = allocate_heretic(center)
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/turf/victim_place = get_step(user, EAST)
	var/mob/living/victim = allocate(/mob/living/carbon/human, victim_place)
	var/obj/blocker = allocate(/obj, get_step(victim, EAST))
	blocker.density = TRUE
	TEST_ASSERT(tide.release(user), "Начального давления хватает на волну без подготовительных ударов.")
	TEST_ASSERT(abs(victim.getBruteLoss() - 26) < 0.001, "Волна и одно столкновение дают 26 ушибов.")
	TEST_ASSERT_EQUAL(get_turf(victim), victim_place, "Преграда останавливает снос.")
	TEST_ASSERT(victim.IsKnockdown(), "Столкновение сбивает противника.")
	TEST_ASSERT_NOTNULL(center.GetComponent(/datum/component/wet_floor), "Волна действительно оставляет скользкий пол.")

/// Давление восстанавливается без противника, а защита от воды переходит вместе с ролью.
/datum/unit_test/heretic_tide_regeneration_and_water/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	var/mob/living/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	TEST_ASSERT(HAS_TRAIT(user, TRAIT_NOSLIPWATER), "Путь сразу защищает от мокрого пола.")
	tide.combat_resource = 0
	COOLDOWN_RESET(tide, ascended_pressure)
	tide.on_life(user)
	TEST_ASSERT_EQUAL(tide.combat_resource, 1, "Без противника восстанавливается единица давления.")
	tide.on_life(user)
	TEST_ASSERT_EQUAL(tide.combat_resource, 1, "Повторный life соблюдает задержку восстановления.")
	ADD_TRAIT(user, TRAIT_NOSLIPWATER, "unit_test")
	var/mob/living/new_body = allocate(/mob/living/carbon/human, get_step(user, NORTH))
	heretic.owner.transfer_to(new_body)
	TEST_ASSERT(HAS_TRAIT(new_body, TRAIT_NOSLIPWATER), "Новое тело получает защиту от воды.")
	TEST_ASSERT(HAS_TRAIT(user, TRAIT_NOSLIPWATER), "Независимый источник защиты старого тела сохраняется.")
	REMOVE_TRAIT(user, TRAIT_NOSLIPWATER, "unit_test")
	TEST_ASSERT(!HAS_TRAIT(user, TRAIT_NOSLIPWATER), "Источник роли снят со старого тела.")
	qdel(tide)
	TEST_ASSERT(!HAS_TRAIT(new_body, TRAIT_NOSLIPWATER), "Удаление знания снимает его защиту.")

/// Волны обновляют короткую лужу без накопления срока и без сокращения уже разлитой воды.
/datum/unit_test/heretic_tide_puddle_duration/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/turf/open/place = get_turf(heretic.owner.current)
	place.ClearWet()
	tide.wet_floor(place)
	var/datum/component/wet_floor/water = place.GetComponent(/datum/component/wet_floor)
	TEST_ASSERT_NOTNULL(water, "Магия оставляет компонент мокрого пола.")
	for(var/pulse_index in 1 to 6)
		tide.wet_floor(place)
	TEST_ASSERT_EQUAL(water.max_time_left(), 15 SECONDS, "Повторные волны не складывают время одной лужи.")
	water.time_left_list["[TURF_WET_WATER]"] = 3 SECONDS
	tide.wet_floor(place)
	TEST_ASSERT_EQUAL(water.max_time_left(), 15 SECONDS, "Подсыхающая лужа обновляется до пятнадцати секунд.")
	place.MakeSlippery(TURF_WET_WATER, min_wet_time = 1 MINUTES)
	tide.wet_floor(place)
	TEST_ASSERT_EQUAL(water.max_time_left(), 1 MINUTES, "Чужая вода с большим сроком не высыхает от волны раньше.")

/// Смерть снимает силу вознесения Пучины при сохранённом вознесении роли, оживление возвращает её.
/datum/unit_test/heretic_tide_ascension_death_recovery/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/final_eldritch/tide_final/finale = heretic.get_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	heretic.ascended = TRUE
	finale.finished = TRUE
	finale.on_body_gain(user)
	TEST_ASSERT_EQUAL(tide.combat_resource_max, 8, "Вознесение даёт запас давления 8.")
	user.death()
	heretic.handle_death(user)
	TEST_ASSERT_EQUAL(tide.combat_resource_max, initial(tide.combat_resource_max), "Смерть возвращает обычный запас давления.")
	TEST_ASSERT(heretic.ascended, "Смерть не отменяет само вознесение роли.")
	user.revive(full_heal = TRUE)
	finale.on_life(user)
	TEST_ASSERT_EQUAL(tide.combat_resource_max, 8, "Оживление возвращает запас давления 8.")
	TEST_ASSERT(tide.release(user, ascended_wave = TRUE), "Оживлённый снова выпускает Голос Пучины.")

/datum/unit_test/proc/tide_flood_puddles(turf/place)
	. = 0
	for(var/obj/effect/heretic_tide_puddle/puddle in place)
		.++

/// Вознёсшаяся Пучина заливает пол в двух клетках без дублей и без скользкой воды, не пропускает её за окна, мочит врагов в воде и в следе и ускоряет героя на своей воде.
/datum/unit_test/heretic_tide_flood/Run()
	var/turf/start = run_loc_floor_bottom_left
	var/datum/antagonist/heretic/heretic = allocate_heretic(start)
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/final_eldritch/tide_final/finale = heretic.get_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	var/turf/near = locate(start.x + 1, start.y + 1, start.z)
	var/turf/edge = locate(start.x + 2, start.y, start.z)
	var/turf/dry = locate(start.x + 3, start.y, start.z)
	var/turf/far = locate(start.x + 4, start.y, start.z)
	var/turf/glazed = locate(start.x, start.y + 1, start.z)
	var/turf/behind_glass = locate(start.x, start.y + 2, start.z)
	allocate(/obj/structure/window/fulltile, glazed)
	var/mob/living/carbon/human/crew = allocate(/mob/living/carbon/human, near)
	var/mob/living/carbon/human/distant = allocate(/mob/living/carbon/human, dry)
	var/mob/living/carbon/human/sheltered = allocate(/mob/living/carbon/human, behind_glass)
	var/mob/living/carbon/human/pursuer = allocate(/mob/living/carbon/human, locate(start.x + 4, start.y + 2, start.z))
	var/mob/living/carbon/human/warded = allocate(/mob/living/carbon/human, locate(start.x + 2, start.y + 2, start.z))
	var/datum/component/anti_magic/ward = warded.AddComponent(/datum/component/anti_magic, TRUE, FALSE, FALSE, null, 5)
	finale.finished = TRUE
	heretic.ascended = TRUE
	finale.on_body_gain(user)
	var/datum/component/heretic_tide_flood/flood = user.GetComponent(/datum/component/heretic_tide_flood)
	TEST_ASSERT_NOTNULL(flood, "Вознесение Пучины заливает пол вокруг героя.")
	flood.flood()
	TEST_ASSERT_EQUAL(tide_flood_puddles(start), 1, "Под героем одна лужа, повторный прилив её обновляет.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(near), 1, "Соседняя клетка залита один раз.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(edge), 1, "Вода доходит до двух клеток.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(dry), 0, "Третья клетка остаётся сухой.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(glazed) + tide_flood_puddles(behind_glass), 0, "Окно не пропускает воду ни на свою клетку, ни за себя.")
	TEST_ASSERT(!sheltered.has_status_effect(/datum/status_effect/heretic_drenched), "Враг за окном сух.")
	TEST_ASSERT_NULL(near.GetComponent(/datum/component/wet_floor), "Прилив не делает пол скользким.")
	var/obj/effect/heretic_tide_puddle/puddle = locate() in near
	TEST_ASSERT(puddle.expires_at > world.time && puddle.expires_at <= world.time + HERETIC_TIDE_FLOOD_LIFETIME, "Лужа живёт недолго и уходит без обновления.")
	var/datum/status_effect/heretic_drenched/water = crew.has_status_effect(/datum/status_effect/heretic_drenched)
	TEST_ASSERT_NOTNULL(water, "Враг в воде намокает.")
	TEST_ASSERT(!distant.has_status_effect(/datum/status_effect/heretic_drenched), "Враг дальше двух клеток сух.")
	TEST_ASSERT(!warded.has_status_effect(/datum/status_effect/heretic_drenched), "Защита от магии не даёт намокнуть.")
	TEST_ASSERT_EQUAL(ward.charges, 5, "Проверка защиты не тратит заряды.")
	water.duration = world.time + 1
	flood.flood()
	TEST_ASSERT_EQUAL(crew.has_status_effect(/datum/status_effect/heretic_drenched), water, "Стоящего в воде прилив не перемачивает заново.")
	TEST_ASSERT_EQUAL(water.duration, world.time + initial(water.duration), "Намокание продлевается на полный срок.")
	distant.forceMove(edge)
	TEST_ASSERT(distant.has_status_effect(/datum/status_effect/heretic_drenched), "Шаг в воду сразу мочит врага.")
	TEST_ASSERT(user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_flow), "На своей воде герой быстрее.")
	user.forceMove(dry)
	TEST_ASSERT_EQUAL(tide_flood_puddles(dry), 1, "Шаг героя оставляет лужу.")
	user.forceMove(far)
	TEST_ASSERT_EQUAL(tide_flood_puddles(far), 1, "След тянется за героем без дублей.")
	TEST_ASSERT(user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_flow), "На ходу герой остаётся в своей воде.")
	pursuer.forceMove(dry)
	TEST_ASSERT(pursuer.has_status_effect(/datum/status_effect/heretic_drenched), "Преследователь в следе намокает.")
	qdel(locate(/obj/effect/heretic_tide_puddle) in far)
	TEST_ASSERT(!user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_flow), "Ушедшая из-под ног вода снимает ускорение.")
	var/list/examine_lines = list()
	SEND_SIGNAL(user, COMSIG_PARENT_EXAMINE, crew, examine_lines)
	TEST_ASSERT(findtext(jointext(examine_lines, " "), "двух клеток"), "Осмотр называет радиус воды.")
	user.death()
	heretic.handle_death(user)
	TEST_ASSERT_NULL(user.GetComponent(/datum/component/heretic_tide_flood), "Смерть снимает прилив.")
	TEST_ASSERT(!user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_flow), "Смерть снимает ускорение.")
	user.revive(full_heal = TRUE)
	finale.on_life(user)
	flood = user.GetComponent(/datum/component/heretic_tide_flood)
	TEST_ASSERT_NOTNULL(flood, "Оживление возвращает прилив.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(far), 1, "Ожившего снова окружает вода.")
	finale.on_body_lose(user)
	TEST_ASSERT_NULL(user.GetComponent(/datum/component/heretic_tide_flood), "Потеря тела снимает прилив.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(far), 0, "Потеря тела убирает воду.")
	TEST_ASSERT(!user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_flow), "Потеря тела снимает ускорение.")
	TEST_ASSERT(!tide.ascension_active, "Потеря тела снимает флаг вознесения.")

/// Направленное окно держит воду только со своей стороны, а окно и перила на клетке героя не глушат прилив.
/datum/unit_test/heretic_tide_flood_edges/Run()
	var/turf/start = run_loc_floor_bottom_left
	var/datum/antagonist/heretic/heretic = allocate_heretic(start)
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/final_eldritch/tide_final/finale = heretic.get_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	var/turf/north = locate(start.x, start.y + 1, start.z)
	var/turf/east = locate(start.x + 1, start.y, start.z)
	var/turf/beyond_east = locate(start.x + 2, start.y, start.z)
	var/turf/diagonal = locate(start.x + 1, start.y + 1, start.z)
	var/obj/structure/window/own_pane = allocate(/obj/structure/window, start)
	own_pane.setDir(NORTH)
	var/obj/structure/railing/rail = allocate(/obj/structure/railing, start)
	rail.setDir(EAST)
	var/obj/structure/window/far_pane = allocate(/obj/structure/window, east)
	far_pane.setDir(EAST)
	finale.finished = TRUE
	heretic.ascended = TRUE
	finale.on_body_gain(user)
	var/datum/component/heretic_tide_flood/flood = user.GetComponent(/datum/component/heretic_tide_flood)
	flood.flood()
	TEST_ASSERT_EQUAL(tide_flood_puddles(start), 1, "Окно и перила на клетке героя не мешают луже под ним.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(east), 1, "Перила и окно на северной грани пропускают воду на восток.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(north), 0, "Окно на клетке героя держит воду со своей стороны.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(diagonal), 1, "Вода обтекает окно через соседнюю клетку.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(beyond_east), 0, "Окно на дальней грани соседней клетки не пропускает воду дальше.")
	TEST_ASSERT(tide.line_clear(start, east), "Цель за перилами на открытой линии.")
	TEST_ASSERT(!tide.line_clear(start, beyond_east), "Окно на дальней грани соседней клетки закрывает линию.")

/// Перенос разума в мёртвое тело снимает прилив и флаг вознесения со старого тела.
/datum/unit_test/heretic_tide_flood_transfer/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/final_eldritch/tide_final/finale = heretic.get_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	finale.finished = TRUE
	heretic.ascended = TRUE
	finale.on_body_gain(user)
	TEST_ASSERT(tide.ascension_active, "Вознесение включено.")
	var/mob/living/carbon/human/corpse = allocate(/mob/living/carbon/human, get_step(user, NORTH))
	corpse.death()
	heretic.owner.transfer_to(corpse)
	TEST_ASSERT_NULL(user.GetComponent(/datum/component/heretic_tide_flood), "Старое тело больше не заливает пол.")
	TEST_ASSERT_NULL(corpse.GetComponent(/datum/component/heretic_tide_flood), "Мёртвое тело не получает прилив.")
	TEST_ASSERT(!tide.ascension_active, "Флаг вознесения снят, хотя разум уже в другом теле.")

/datum/unit_test/proc/ascend_tide_flood(turf/place)
	var/datum/antagonist/heretic/heretic = allocate_heretic(place)
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	var/datum/eldritch_knowledge/final_eldritch/tide_final/finale = heretic.get_knowledge(/datum/eldritch_knowledge/final_eldritch/tide_final)
	finale.finished = TRUE
	heretic.ascended = TRUE
	finale.on_body_gain(heretic.owner.current)
	return heretic

/// Лужи прилива: срок прежний, ушедшая вода в срок и раньше стекает отпечатком, шаг по своей воде даёт брызги не чаще раза в 0.3 с и только при зрителях.
/datum/unit_test/heretic_tide_puddle_visuals/Run()
	var/turf/start = run_loc_floor_bottom_left
	var/datum/antagonist/heretic/heretic = ascend_tide_flood(start)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/component/heretic_tide_flood/flood = user.GetComponent(/datum/component/heretic_tide_flood)
	flood.flood()
	var/turf/near = locate(start.x + 1, start.y + 1, start.z)
	var/obj/effect/heretic_tide_puddle/puddle = locate() in near
	TEST_ASSERT_NOTNULL(puddle, "Прилив заливает пол, как раньше.")
	TEST_ASSERT(timeleft(puddle.expiry_timer) <= HERETIC_TIDE_FLOOD_LIFETIME + DAMAGE_PRECISION, "Лужа живёт прежние 4 секунды.")
	TEST_ASSERT(puddle.mouse_opacity == MOUSE_OPACITY_TRANSPARENT, "Лужа не мешает кликам.")
	qdel(puddle)
	TEST_ASSERT_EQUAL(tide_flood_puddles(near), 0, "Сама лужа убрана сразу.")
	var/obj/effect/temp_visual/heretic_vfx/ghost/drain = locate() in near
	TEST_ASSERT_NOTNULL(drain, "Убранная раньше срока вода стекает, а не пропадает.")
	TEST_ASSERT_EQUAL(drain.plane, FLOOR_PLANE, "Стекающий отпечаток лежит на полу.")
	TEST_ASSERT(wait_for_qdeleted(drain), "Отпечаток стекает до конца.")
	var/turf/far = run_loc_floor_top_right
	var/obj/effect/heretic_tide_puddle/expiring = new(far, flood)
	TEST_ASSERT(wait_for_qdeleted(expiring, HERETIC_TIDE_FLOOD_LIFETIME + 1 SECONDS), "Лужа без хозяина рядом уходит по сроку.")
	var/obj/effect/temp_visual/heretic_vfx/ghost/expired_drain = locate() in far
	TEST_ASSERT_NOTNULL(expired_drain, "Вода, ушедшая в срок, тоже стекает отпечатком.")
	var/turf/place = get_turf(user)
	var/list/before = list_vfx_bursts(place)
	flood.splash_step(place)
	var/obj/effect/temp_visual/heretic_vfx/burst/splash = find_vfx_burst(place, /particles/heretic_ascension/tide/step, before)
	TEST_ASSERT_NOTNULL(splash, "Из-под шага по своей воде летят брызги.")
	TEST_ASSERT_NULL(splash.glow, "Брызги не светятся сами.")
	TEST_ASSERT(!COOLDOWN_FINISHED(flood, step_splash), "Брызги не чаще раза в 0.3 секунды.")
	var/turf/next = get_step(place, EAST)
	var/list/next_before = list_vfx_bursts(next)
	COOLDOWN_RESET(flood, step_splash)
	user.forceMove(next)
	TEST_ASSERT_NULL(find_vfx_burst(next, /particles/heretic_ascension/tide/step, next_before), "Без зрителей рядом брызги не рисуются.")
	TEST_ASSERT_EQUAL(tide_flood_puddles(next), 1, "Шаг оставляет лужу, как раньше.")
	TEST_ASSERT(wait_for_qdeleted(splash), "Брызги опадают.")

/// С намокшего капает вода вместо лужи-наклейки под ним; замена воды не копит капли, снятие отпускает последние.
/datum/unit_test/heretic_tide_drenched_drips/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/mob/living/carbon/human/victim = allocate(/mob/living/carbon/human, get_step(run_loc_floor_bottom_left, EAST))
	tide.soak(victim)
	var/datum/status_effect/heretic_drenched/water = victim.has_status_effect(/datum/status_effect/heretic_drenched)
	TEST_ASSERT_NOTNULL(water, "Вода Пучины мочит цель, как раньше.")
	TEST_ASSERT(victim.has_movespeed_modifier(/datum/movespeed_modifier/heretic_drenched), "Замедление прежнее.")
	var/obj/effect/abstract/heretic_particle_holder/drips = water.drips
	TEST_ASSERT_NOTNULL(drips, "С намокшего капает вода.")
	TEST_ASSERT(drips in victim.vis_contents, "Капли идут от самой цели.")
	TEST_ASSERT(drips.particles.count <= 10, "Капель немного.")
	TEST_ASSERT_NULL(drips.glow, "Капли не светятся сами.")
	for(var/mutable_appearance/overlay as anything in victim.overlays)
		TEST_ASSERT(overlay.icon_state != "tide_puddle", "Под намокшим больше нет лужи-наклейки.")
	tide.soak(victim)
	var/holders = 0
	for(var/obj/effect/abstract/heretic_particle_holder/holder in victim.vis_contents)
		holders++
	TEST_ASSERT_EQUAL(holders, 1, "Повторное намокание не копит капли.")
	TEST_ASSERT(QDELETED(drips) || drips.loc == get_turf(victim), "Прежние капли падают на пол.")
	var/datum/status_effect/heretic_drenched/fresh_water = victim.has_status_effect(/datum/status_effect/heretic_drenched)
	var/obj/effect/abstract/heretic_particle_holder/last_drips = fresh_water.drips
	victim.remove_status_effect(/datum/status_effect/heretic_drenched)
	TEST_ASSERT(!(last_drips in victim.vis_contents), "Высохшая цель больше не капает.")
	TEST_ASSERT(QDELETED(last_drips) || !last_drips.particles.spawning, "Новые капли не появляются.")
	TEST_ASSERT(wait_for_qdeleted(last_drips), "Последние капли падают и исчезают.")

/// Голос Пучины: вода встаёт короной вокруг героя, волна и пена расходятся, пол дрожит; урон прежний.
/datum/unit_test/heretic_tide_voice_visuals/Run()
	var/turf/start = run_loc_floor_bottom_left
	var/datum/antagonist/heretic/heretic = ascend_tide_flood(start)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/mob/living/carbon/human/victim = allocate(/mob/living/carbon/human, locate(start.x + 2, start.y, start.z))
	var/list/before = list_vfx_bursts(start)
	TEST_ASSERT(tide.release(user, ascended_wave = TRUE), "Голос Пучины звучит.")
	TEST_ASSERT(abs(victim.getBruteLoss() - 30) <= DAMAGE_PRECISION, "Урон прежний: 30 ушибов.")
	TEST_ASSERT(abs(victim.getStaminaLoss() - 40) <= DAMAGE_PRECISION, "Выносливость прежняя: 40.")
	var/obj/effect/temp_visual/heretic_tide_swell/back = locate() in start
	var/obj/effect/temp_visual/heretic_tide_swell/front/front = locate() in start
	TEST_ASSERT_NOTNULL(back, "Вода встаёт короной за героем.")
	TEST_ASSERT_NOTNULL(front, "Вода встаёт короной перед героем.")
	TEST_ASSERT(back.layer < MOB_LAYER && front.layer > MOB_LAYER, "Корона обнимает героя спереди и сзади.")
	var/obj/effect/temp_visual/heretic_vfx/shockwave/wave = locate() in start
	TEST_ASSERT_NOTNULL(wave, "От героя идёт волна.")
	var/obj/effect/temp_visual/heretic_vfx/burst/foam = find_vfx_burst(start, /particles/heretic_ascension/tide/foam, before)
	TEST_ASSERT_NOTNULL(foam, "Пена разлетается.")
	TEST_ASSERT(wait_for_qdeleted(back) && wait_for_qdeleted(front) && wait_for_qdeleted(wave), "Корона и волна опадают.")
	TEST_ASSERT(wait_for_qdeleted(foam, 3 SECONDS), "Пена оседает.")

/datum/unit_test/heretic_tide_visual_types_create_and_destroy/Run()
	for(var/thing_type in list(/obj/effect/temp_visual/heretic_tide_swell, /obj/effect/temp_visual/heretic_tide_swell/front, /obj/effect/temp_visual/heretic_tide/spill, /obj/effect/abstract/heretic_vfx_attached/tide_choke))
		var/atom/movable/thing = new thing_type(run_loc_floor_bottom_left)
		qdel(thing)
		TEST_ASSERT(QDELETED(thing), "[thing_type] удаляется без ошибок.")

/datum/unit_test/proc/tide_breach_puddles(turf/place)
	. = 0
	for(var/obj/effect/heretic_tide_puddle/breach/puddle in place)
		.++

/// Хватка по раковине открывает прорыв: вода в двух клетках мочит врагов и ускоряет еретика, дело, улика, предел с вытеснением, обновление и срок; ключ и нулевой жезл закрывают прорыв в раковине, душе и баке, не ломая их, после закрытия ключ работает как обычно; смерть еретика прорывы не трогает, удаление знания снимает.
/datum/unit_test/heretic_tide_breach/Run()
	var/datum/antagonist/heretic/heretic = allocate_deed_heretic(PATH_TIDE)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/turf/open/origin = get_turf(user)
	var/obj/structure/sink/sink = allocate(/obj/structure/sink, get_step(user, NORTHEAST))
	var/mob/living/carbon/human/crew = allocate(/mob/living/carbon/human, locate(sink.x + 2, sink.y, sink.z))
	var/obj/item/melee/touch_attack/mansus_fist/fist = allocate(/obj/item/melee/touch_attack/mansus_fist)
	fist.afterattack(sink, user, TRUE)
	TEST_ASSERT_EQUAL(length(tide.breaches), 1, "Хватка по раковине открывает прорыв.")
	TEST_ASSERT_EQUAL(tide.breaches[1], sink, "Прорыв открыт в этой раковине.")
	TEST_ASSERT_NOTNULL(heretic_craft_on(sink, "tide_breach"), "Прорыв несёт ремесло Пучины.")
	TEST_ASSERT_EQUAL(tide_breach_puddles(get_turf(sink)), 1, "Вода стоит у самого источника.")
	TEST_ASSERT_EQUAL(tide_breach_puddles(get_turf(crew)), 1, "Вода доходит до двух клеток.")
	TEST_ASSERT_EQUAL(tide_breach_puddles(locate(sink.x + 3, sink.y, sink.z)), 0, "Третья клетка сухая.")
	TEST_ASSERT_NULL(origin.GetComponent(/datum/component/wet_floor), "Вода прорыва не делает пол скользким.")
	TEST_ASSERT(crew.has_status_effect(/datum/status_effect/heretic_drenched), "Враг в воде прорыва намокает.")
	TEST_ASSERT(user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_sea), "На своей воде еретик быстрее.")
	TEST_ASSERT_EQUAL(heretic.deed.progress, 1, "Прорыв продвигает дело.")
	var/obj/effect/decal/cleanable/heretic_trace/trace = locate() in get_turf(sink)
	TEST_ASSERT_NOTNULL(trace, "След дела остаётся у источника.")
	allocated += trace
	TEST_ASSERT(findtext(jointext(sink.examine(crew), " "), "не уходит в слив"), "Экипаж видит улику при осмотре.")
	TEST_ASSERT(findtext(jointext(sink.examine(user), " "), "Ваше ремесло"), "Еретик узнаёт свой прорыв.")
	var/list/resource = tide.get_combat_resource_data()
	TEST_ASSERT(findtext(resource["state"], "Прорывов: 1 из [HERETIC_TIDE_BREACH_LIMIT]"), "Запас силы считает прорывы.")
	TEST_ASSERT(!tide.on_mansus_grasp(sink, user, TRUE, null), "Второй прорыв в том же источнике не открывается.")
	TEST_ASSERT(findtext(tide.grasp_failure_reason, "уже открыт"), "Отказ называет открытый прорыв.")
	var/obj/machinery/shower/shower = allocate(/obj/machinery/shower, locate(origin.x + 4, origin.y, origin.z))
	var/obj/structure/reagent_dispensers/watertank/tank = allocate(/obj/structure/reagent_dispensers/watertank, locate(origin.x + 4, origin.y + 4, origin.z))
	var/obj/structure/sink/second_sink = allocate(/obj/structure/sink, locate(origin.x, origin.y + 4, origin.z))
	for(var/atom/source as anything in list(shower, tank, second_sink))
		TEST_ASSERT(tide.open_breach(source, user), "Прорыв открывается: [source].")
	TEST_ASSERT_EQUAL(length(tide.breaches), HERETIC_TIDE_BREACH_LIMIT, "Держатся три прорыва.")
	TEST_ASSERT(!(sink in tide.breaches), "Новый прорыв сверх предела вытесняет старейший.")
	TEST_ASSERT_NULL(heretic_craft_on(sink, "tide_breach"), "Вытесненный прорыв снимает ремесло.")
	TEST_ASSERT_EQUAL(tide.breaches[1], shower, "Старейшим становится следующий прорыв.")
	var/datum/heretic_tide_breach/breach = tide.breaches[shower]
	TEST_ASSERT(abs(timeleft(breach.refresh_timer) - HERETIC_TIDE_BREACH_REFRESH) <= 1, "Вода обновляется раз в 20 секунд.")
	TEST_ASSERT(abs(timeleft(breach.expiry_timer) - HERETIC_TIDE_BREACH_LIFETIME) <= 1, "Прорыв держится 5 минут.")
	var/turf/shore = locate(shower.x - 1, shower.y + 1, shower.z)
	qdel(locate(/obj/effect/heretic_tide_puddle/breach) in shore)
	TEST_ASSERT_EQUAL(tide_breach_puddles(shore), 0, "Лужа у душа убрана.")
	breach.flood()
	TEST_ASSERT_EQUAL(tide_breach_puddles(shore), 1, "Обновление возвращает воду.")
	tide.on_death(user)
	TEST_ASSERT_EQUAL(length(tide.breaches), HERETIC_TIDE_BREACH_LIMIT, "Смерть еретика не закрывает прорывы.")
	var/mob/living/carbon/human/mechanic = allocate(/mob/living/carbon/human, locate(origin.x + 2, origin.y + 2, origin.z))
	var/obj/item/wrench/wrench = allocate(/obj/item/wrench)
	mechanic.put_in_hands(wrench)
	wrench.melee_attack_chain(mechanic, shower)
	TEST_ASSERT(!(shower in tide.breaches), "Гаечный ключ закрывает прорыв в душе.")
	TEST_ASSERT(!QDELETED(shower) && shower.watertemp == "normal", "Ключ по прорыву не крутит вентиль душа.")
	TEST_ASSERT_EQUAL(tide_breach_puddles(shore), 0, "Закрытый прорыв забирает воду.")
	SEND_SIGNAL(mechanic, COMSIG_ENABLE_COMBAT_MODE)
	TEST_ASSERT(SEND_SIGNAL(mechanic, COMSIG_COMBAT_MODE_CHECK, COMBAT_MODE_ACTIVE), "Механик в боевом режиме.")
	wrench.melee_attack_chain(mechanic, second_sink)
	TEST_ASSERT(!(second_sink in tide.breaches), "Ключ в боевом режиме тоже закрывает прорыв.")
	TEST_ASSERT(!QDELETED(second_sink), "Закрытие прорыва не разбирает раковину.")
	SEND_SIGNAL(mechanic, COMSIG_DISABLE_COMBAT_MODE)
	var/turf/second_sink_turf = get_turf(second_sink)
	wrench.melee_attack_chain(mechanic, second_sink)
	TEST_ASSERT(QDELETED(second_sink), "Без прорыва ключ снова разбирает раковину.")
	for(var/obj/item/stack/sheet/metal/leftover in second_sink_turf)
		qdel(leftover)
	var/mob/living/carbon/human/chaplain = allocate(/mob/living/carbon/human, locate(origin.x + 2, origin.y + 1, origin.z))
	var/obj/item/nullrod/rod = allocate(/obj/item/nullrod)
	chaplain.put_in_hands(rod)
	TEST_ASSERT(tide.open_breach(sink, user), "Прорыв снова открывается в раковине.")
	TEST_ASSERT(tide.open_breach(shower, user), "Прорыв снова открывается в душе.")
	for(var/atom/source as anything in list(sink, shower, tank))
		rod.melee_attack_chain(chaplain, source)
		TEST_ASSERT(!(source in tide.breaches), "Нулевой жезл закрывает прорыв: [source].")
		TEST_ASSERT_NULL(heretic_craft_on(source, "tide_breach"), "Жезл снимает ремесло: [source].")
		TEST_ASSERT(!QDELETED(source), "Жезл не ломает источник: [source].")
	TEST_ASSERT_EQUAL(tide_breach_puddles(get_turf(tank)), 0, "Вода у бака ушла.")
	TEST_ASSERT(tide.open_breach(tank, user), "Прорыв снова открывается в баке.")
	wrench.melee_attack_chain(mechanic, tank)
	TEST_ASSERT(!(tank in tide.breaches), "Гаечный ключ закрывает прорыв в баке.")
	TEST_ASSERT(!tank.leaking && !tank.anchored, "Ключ по прорыву не открывает кран бака и не крепит его.")
	wrench.melee_attack_chain(mechanic, tank)
	TEST_ASSERT(tank.leaking, "Без прорыва ключ снова открывает кран бака.")
	tank.leaking = FALSE
	TEST_ASSERT(tide.open_breach(shower, user), "Прорыв в душе открывается в третий раз.")
	breach = tide.breaches[shower]
	breach.expire()
	TEST_ASSERT(!(shower in tide.breaches), "По сроку прорыв закрывается сам.")
	TEST_ASSERT(QDELETED(breach), "Истёкший прорыв удалён.")
	TEST_ASSERT(tide.open_breach(sink, user), "Перед удалением знания открыт прорыв.")
	qdel(tide)
	TEST_ASSERT_NULL(heretic_craft_on(sink, "tide_breach"), "Удаление знания закрывает прорывы.")
	TEST_ASSERT_EQUAL(tide_breach_puddles(get_turf(sink)), 0, "Удаление знания убирает воду.")

/obj/item/radio/headset/tide_drown_probe
	var/transmissions = 0

/obj/item/radio/headset/tide_drown_probe/talk_into(mob/living/speaker, message, channel, list/spans, datum/language/language)
	transmissions++
	return ITALICS | REDUCE_RANGE

/datum/unit_test/proc/await_tide_drowning(mob/living/victim)
	var/list/budget = new_wait_budget(HERETIC_TIDE_DROWN_TELEGRAPH + 2 SECONDS, "захлёб Пучины на [victim]")
	while(!victim.has_status_effect(/datum/status_effect/heretic_tide_drowning))
		if(!wait_budget_tick(budget))
			break
	return victim.has_status_effect(/datum/status_effect/heretic_tide_drowning)

/// Захлебнуться берёт только цель на мокром полу: намокшая на сухом, дальняя и защищённая отказываются; немота глушит голос и рацию, удушье растёт не выше 50; вытащенная на сухой пол и тронутая нулевым жезлом цель вырывается без беспамятства; на воде прорыва цель теряет сознание на 10 секунд, готова к обряду и минуту после пробуждения невосприимчива; смерть еретика снимает захлёб.
/datum/unit_test/heretic_tide_drown/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_drown)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/spell/tide_drown/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/spell/tide_drown)
	var/obj/effect/proc_holder/spell/pointed/heretic_tide/drown/spell = knowledge.granted_spell
	TEST_ASSERT(istype(spell), "Знание выдаёт Захлебнуться.")
	TEST_ASSERT_EQUAL(spell.charge_max, 40 SECONDS, "Перезарядка 40 секунд.")
	var/turf/origin = get_turf(user)
	var/mob/living/carbon/human/victim = allocate(/mob/living/carbon/human, locate(origin.x + 2, origin.y, origin.z))
	tide.combat_resource = 4
	tide.soak(victim)
	TEST_ASSERT_NOTNULL(victim.has_status_effect(/datum/status_effect/heretic_drenched), "Цель промокла.")
	TEST_ASSERT(!spell.can_target(victim, user, TRUE), "Промокшая цель на сухом полу не выбирается.")
	TEST_ASSERT(!tide.drown(user, victim), "Одной мокрой одежды мало.")
	TEST_ASSERT(findtext(tide.tide_failure, "мокром полу"), "Отказ называет мокрый пол: [tide.tide_failure]")
	tide.wet_floor(get_turf(victim))
	TEST_ASSERT(tide.on_wet_floor(victim), "Лужа от Сброса считается мокрым полом.")
	var/datum/component/anti_magic/protection = victim.AddComponent(/datum/component/anti_magic, TRUE, FALSE, FALSE, null, 5)
	TEST_ASSERT(!tide.drown(user, victim), "Антимагия отталкивает захват.")
	TEST_ASSERT(findtext(tide.tide_failure, "защищена от магии"), "Отказ называет антимагию: [tide.tide_failure]")
	TEST_ASSERT_EQUAL(protection.charges, 5, "Проверка не тратит заряды антимагии.")
	qdel(protection)
	var/mob/living/carbon/human/distant = allocate(/mob/living/carbon/human, locate(origin.x + 5, origin.y, origin.z))
	tide.wet_floor(get_turf(distant))
	TEST_ASSERT(!tide.drown(user, distant), "Цель дальше четырёх клеток не захлёбывается.")
	TEST_ASSERT(findtext(tide.tide_failure, "четырёх клеток"), "Отказ называет дальность: [tide.tide_failure]")
	TEST_ASSERT_EQUAL(tide.combat_resource, 4, "Отказы не тратят давление.")
	var/obj/item/radio/headset/tide_drown_probe/headset = allocate(/obj/item/radio/headset/tide_drown_probe)
	TEST_ASSERT(victim.equip_to_slot_if_possible(headset, ITEM_SLOT_EARS_LEFT), "Цель надевает гарнитуру.")
	victim.say(";Проверка связи.", language = /datum/language/common, ignore_spam = TRUE)
	TEST_ASSERT_EQUAL(headset.transmissions, 1, "До захвата цель говорит в рацию.")
	TEST_ASSERT(spell.can_target(victim, user, TRUE), "Цель в луже выбирается.")
	TEST_ASSERT(tide.drown(user, victim), "Цель в луже захлёбывается.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 2, "Захват стоит два давления.")
	var/datum/status_effect/heretic_tide_drowning/drowning = await_tide_drowning(victim)
	TEST_ASSERT_NOTNULL(drowning, "Цель захлёбывается.")
	var/remaining = drowning.duration - world.time
	TEST_ASSERT(remaining < HERETIC_TIDE_DROWN_DURATION + 1 && remaining > HERETIC_TIDE_DROWN_DURATION - 1 SECONDS, "Захлёб длится 5 секунд: осталось [remaining] дс.")
	TEST_ASSERT(HAS_TRAIT(victim, TRAIT_MUTE), "Захлёбывающаяся цель немеет.")
	victim.say(";Помогите!", language = /datum/language/common, ignore_spam = TRUE)
	TEST_ASSERT_EQUAL(headset.transmissions, 1, "Немота глушит и рацию.")
	TEST_ASSERT(!tide.drown(user, victim), "Второй захлёб на ту же цель не накладывается.")
	var/oxy_before = victim.getOxyLoss()
	drowning.tick()
	TEST_ASSERT(abs(victim.getOxyLoss() - oxy_before - 6) <= DAMAGE_PRECISION, "Удушье растёт на 6 в секунду: [victim.getOxyLoss()].")
	victim.adjustOxyLoss(HERETIC_TIDE_DROWN_OXY_CAP - 3 - victim.getOxyLoss())
	drowning.tick()
	TEST_ASSERT(abs(victim.getOxyLoss() - HERETIC_TIDE_DROWN_OXY_CAP) <= DAMAGE_PRECISION, "Удушье от захвата не выше 50: [victim.getOxyLoss()].")
	drowning.tick()
	TEST_ASSERT(abs(victim.getOxyLoss() - HERETIC_TIDE_DROWN_OXY_CAP) <= DAMAGE_PRECISION, "На пределе удушье не растёт: [victim.getOxyLoss()].")
	var/turf/dry_spot = locate(origin.x + 2, origin.y + 1, origin.z)
	TEST_ASSERT_NULL(dry_spot.GetComponent(/datum/component/wet_floor), "Соседняя клетка сухая.")
	victim.forceMove(dry_spot)
	TEST_ASSERT(!QDELETED(drowning), "Шаг на сухой пол не обрывает захлёб сразу.")
	drowning.dry_since = world.time - HERETIC_TIDE_DROWN_DRY_GRACE
	drowning.tick()
	TEST_ASSERT(QDELETED(drowning), "Полторы секунды на сухом полу - и цель вырывается, хоть и промокла.")
	TEST_ASSERT_NOTNULL(victim.has_status_effect(/datum/status_effect/heretic_drenched), "Намокание при этом осталось.")
	TEST_ASSERT(!HAS_TRAIT(victim, TRAIT_MUTE), "Вырвавшаяся цель снова говорит.")
	TEST_ASSERT(!victim.IsUnconscious(), "Вырвавшаяся цель в сознании.")
	var/mob/living/carbon/human/rescued = allocate(/mob/living/carbon/human, locate(origin.x + 2, origin.y + 2, origin.z))
	tide.wet_floor(get_turf(rescued))
	tide.combat_resource = 4
	TEST_ASSERT(tide.drown(user, rescued), "Вторая цель в луже захлёбывается.")
	drowning = await_tide_drowning(rescued)
	TEST_ASSERT_NOTNULL(drowning, "Вторая цель захлёбывается.")
	var/mob/living/carbon/human/chaplain = allocate(/mob/living/carbon/human, locate(origin.x + 3, origin.y + 2, origin.z))
	var/obj/item/nullrod/rod = allocate(/obj/item/nullrod)
	chaplain.put_in_hands(rod)
	rod.melee_attack_chain(chaplain, rescued)
	TEST_ASSERT(QDELETED(drowning), "Нулевой жезл развеивает захлёб.")
	TEST_ASSERT(!HAS_TRAIT(rescued, TRAIT_MUTE), "После жезла цель снова говорит.")
	TEST_ASSERT(!rescued.IsUnconscious(), "После жезла цель в сознании.")
	TEST_ASSERT_EQUAL(rescued.getBruteLoss(), 0, "Жезл не бьёт цель.")
	TEST_ASSERT(findtext(heretic_capture_block_reason(user, rescued, "tide"), "приходит в себя"), "После жезла цель минуту невосприимчива.")
	var/obj/structure/sink/sink = allocate(/obj/structure/sink, locate(origin.x + 5, origin.y + 5, origin.z))
	TEST_ASSERT(tide.open_breach(sink, user), "Прорыв даёт воду.")
	var/mob/living/carbon/human/swimmer = allocate(/mob/living/carbon/human, locate(origin.x + 3, origin.y + 3, origin.z))
	swimmer.remove_status_effect(/datum/status_effect/heretic_drenched)
	TEST_ASSERT(tide.on_own_water(swimmer), "Цель стоит на воде прорыва.")
	TEST_ASSERT(tide.drown(user, swimmer), "Цель на своей воде захлёбывается и не промокнув.")
	drowning = await_tide_drowning(swimmer)
	TEST_ASSERT_NOTNULL(drowning, "Цель на воде прорыва захлёбывается.")
	swimmer.forceMove(locate(origin.x + 3, origin.y + 4, origin.z))
	TEST_ASSERT(!QDELETED(drowning), "Шаг по воде не обрывает захлёб.")
	drowning.duration = world.time
	TEST_ASSERT(wait_for_qdeleted(drowning, 1 SECONDS), "Захлёб заканчивается.")
	TEST_ASSERT(swimmer.IsUnconscious(), "Цель на воде теряет сознание.")
	TEST_ASSERT(swimmer.AmountUnconscious() > HERETIC_TIDE_DROWN_SLEEP - 1 SECONDS && swimmer.AmountUnconscious() <= HERETIC_TIDE_DROWN_SLEEP + DAMAGE_PRECISION, "Беспамятство 10 секунд: [swimmer.AmountUnconscious()] дс.")
	TEST_ASSERT(heretic.hunt_target_ready(swimmer), "Потерявшая сознание цель готова к обряду.")
	TEST_ASSERT(!HAS_TRAIT(swimmer, TRAIT_MUTE), "Немота снята.")
	TEST_ASSERT(findtext(heretic_capture_block_reason(user, swimmer, "tide"), "приходит в себя"), "После захлёба цель минуту невосприимчива.")
	var/datum/status_effect/heretic_capture_immunity/drowned = capture_immunity(swimmer, "tide")
	TEST_ASSERT(abs(drowned.duration - world.time - swimmer.AmountUnconscious() - HERETIC_CAPTURE_IMMUNITY) < 1, "Минута невосприимчивости отсчитывается от пробуждения: [drowned.duration - world.time] дс.")
	TEST_ASSERT(!tide.drown(user, swimmer), "Невосприимчивую цель не захлебнуть.")
	var/mob/living/carbon/human/gasping = allocate(/mob/living/carbon/human, locate(origin.x + 1, origin.y + 2, origin.z))
	tide.wet_floor(get_turf(gasping))
	tide.combat_resource = 4
	TEST_ASSERT(tide.drown(user, gasping), "Третья цель захлёбывается.")
	drowning = await_tide_drowning(gasping)
	TEST_ASSERT_NOTNULL(drowning, "Третья цель захлёбывается.")
	gasping.adjustOxyLoss(HERETIC_TIDE_DROWN_OXY_CAP + 5)
	var/oxy_above = gasping.getOxyLoss()
	drowning.tick()
	TEST_ASSERT(abs(gasping.getOxyLoss() - oxy_above) <= DAMAGE_PRECISION, "Цель выше предела захват не душит дальше.")
	gasping.adjustOxyLoss(-gasping.getOxyLoss())
	tide.on_death(user)
	TEST_ASSERT(QDELETED(drowning), "Смерть еретика обрывает захлёб.")
	TEST_ASSERT(!HAS_TRAIT(gasping, TRAIT_MUTE), "Оборванный захлёб снимает немоту.")
	TEST_ASSERT(!gasping.IsUnconscious(), "Оборванный захлёб не усыпляет.")

/datum/unit_test/proc/await_tide_spill(turf/place)
	var/list/budget = new_wait_budget(2 SECONDS, "лужица захлёба на [place]")
	while(!(locate(/obj/effect/temp_visual/heretic_tide/spill) in place))
		if(!wait_budget_tick(budget))
			break
	return locate(/obj/effect/temp_visual/heretic_tide/spill) in place

/// Захлёб виден у рта: чёрная вода поворачивается и ложится вместе с телом; спасённая на сухом полу, жезлом или растолкавшим цель выплёвывает воду в лужицу перед собой, смерть и удаление тела просто гасят воду.
/datum/unit_test/heretic_tide_choke_visuals/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_drown)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/turf/origin = get_turf(user)
	var/list/spots = list("dry" = list(2, 0), "rod" = list(1, 2), "shaken" = list(2, 2), "dead" = list(3, 2), "deleted" = list(2, 3))
	var/list/victims = list()
	for(var/role in spots)
		var/list/offset = spots[role]
		var/mob/living/carbon/human/victim = allocate(/mob/living/carbon/human, locate(origin.x + offset[1], origin.y + offset[2], origin.z))
		tide.wet_floor(get_turf(victim))
		tide.combat_resource = 4
		TEST_ASSERT(tide.drown(user, victim), "Цель «[role]» в луже захлёбывается.")
		victims[role] = victim
	var/list/chokes = list()
	for(var/role in victims)
		var/mob/living/carbon/human/victim = victims[role]
		var/datum/status_effect/heretic_tide_drowning/drowning = await_tide_drowning(victim)
		TEST_ASSERT_NOTNULL(drowning, "Цель «[role]» захлёбывается.")
		var/obj/effect/abstract/heretic_vfx_attached/tide_choke/choke = drowning.choke
		TEST_ASSERT_NOTNULL(choke, "Изо рта цели «[role]» льётся чёрная вода.")
		TEST_ASSERT(choke in victim.vis_contents, "Вода держится на самой цели.")
		chokes[role] = choke
	var/obj/effect/abstract/heretic_vfx_attached/tide_choke/choke = chokes["dry"]
	TEST_ASSERT_EQUAL(choke.icon_state, "tide_choke", "Пока цель захлёбывается, вода течёт изо рта.")
	TEST_ASSERT(choke.icon_state in icon_states(choke.icon), "Состояние захлёба есть в ресурсе.")
	TEST_ASSERT("tide_choke_spit" in icon_states(choke.icon), "Состояние выплеска есть в ресурсе.")
	TEST_ASSERT(choke.vis_flags & VIS_INHERIT_DIR, "Вода поворачивается вместе с целью.")
	TEST_ASSERT(!(choke.appearance_flags & RESET_TRANSFORM), "Упавшая цель роняет воду вместе с головой.")
	TEST_ASSERT_NULL(choke.glow, "Чёрная вода сама не светится.")
	var/matrix/raised = choke.transform
	TEST_ASSERT(raised.f > 0, "Рисунок поднят, чтобы пузыри успели всплыть над головой.")
	var/mob/living/carbon/human/rescued = victims["dry"]
	var/datum/status_effect/heretic_tide_drowning/dry_drowning = rescued.has_status_effect(/datum/status_effect/heretic_tide_drowning)
	var/turf/dry_spot = locate(origin.x + 3, origin.y + 1, origin.z)
	rescued.forceMove(dry_spot)
	TEST_ASSERT(!tide.on_wet_floor(rescued), "Цель вышла на сухой пол.")
	rescued.setDir(EAST)
	dry_drowning.dry_since = world.time - HERETIC_TIDE_DROWN_DRY_GRACE
	dry_drowning.tick()
	TEST_ASSERT(QDELETED(dry_drowning), "На сухом полу захлёб кончается.")
	TEST_ASSERT(!QDELETED(choke) && choke.icon_state == "tide_choke_spit", "Спасённая цель выплёвывает воду.")
	var/matrix/level = choke.transform
	TEST_ASSERT_EQUAL(level.f, 0, "Выплеск рисуется от рта до ног без подъёма.")
	var/obj/effect/temp_visual/heretic_tide/spill/spill = await_tide_spill(dry_spot)
	TEST_ASSERT_NOTNULL(spill, "Выплеснутая вода растекается лужицей.")
	TEST_ASSERT(spill.icon_state in icon_states(spill.icon), "Состояние лужицы есть в ресурсе.")
	TEST_ASSERT_EQUAL(spill.plane, FLOOR_PLANE, "Лужица лежит на полу.")
	TEST_ASSERT(spill.pixel_x > 0 && !spill.pixel_y, "Вода падает перед лицом цели, смотрящей на восток.")
	TEST_ASSERT_NULL(dry_spot.GetComponent(/datum/component/wet_floor), "Лужица - только картинка, пол не мокнет.")
	TEST_ASSERT(wait_for_qdeleted(choke), "Выплеск гаснет.")
	TEST_ASSERT(!(choke in rescued.vis_contents), "Погасшая вода снята с цели.")
	TEST_ASSERT(wait_for_qdeleted(spill), "Лужица уходит.")
	var/mob/living/carbon/human/blessed = victims["rod"]
	var/mob/living/carbon/human/chaplain = allocate(/mob/living/carbon/human, locate(origin.x, origin.y + 2, origin.z))
	var/obj/item/nullrod/rod = allocate(/obj/item/nullrod)
	chaplain.put_in_hands(rod)
	rod.melee_attack_chain(chaplain, blessed)
	choke = chokes["rod"]
	TEST_ASSERT_NULL(blessed.has_status_effect(/datum/status_effect/heretic_tide_drowning), "Жезл развеивает захлёб.")
	TEST_ASSERT(!QDELETED(choke) && choke.icon_state == "tide_choke_spit", "После жезла вода выплёскивается из горла.")
	var/mob/living/carbon/human/shaken = victims["shaken"]
	SEND_SIGNAL(shaken, COMSIG_LIVING_HERETIC_CAPTURE_SHAKEN, chaplain)
	choke = chokes["shaken"]
	TEST_ASSERT_NULL(shaken.has_status_effect(/datum/status_effect/heretic_tide_drowning), "Растолканная цель вырывается.")
	TEST_ASSERT(!QDELETED(choke) && choke.icon_state == "tide_choke_spit", "Растолканная цель выкашливает воду.")
	var/mob/living/carbon/human/dead = victims["dead"]
	var/datum/status_effect/heretic_tide_drowning/dead_drowning = dead.has_status_effect(/datum/status_effect/heretic_tide_drowning)
	dead.death()
	if(!QDELETED(dead_drowning))
		dead_drowning.tick()
	choke = chokes["dead"]
	TEST_ASSERT(QDELETED(dead_drowning), "Смерть обрывает захлёб.")
	TEST_ASSERT(QDELETED(choke) || choke.icon_state == "tide_choke", "У мёртвого вода не выплёскивается.")
	TEST_ASSERT(wait_for_qdeleted(choke), "Вода у мёртвого гаснет.")
	TEST_ASSERT(!(choke in dead.vis_contents), "Погасшая вода снята с тела.")
	TEST_ASSERT_NULL(locate(/obj/effect/temp_visual/heretic_tide/spill) in get_turf(dead), "Под мёртвым лужица не растекается.")
	var/mob/living/carbon/human/deleted = victims["deleted"]
	choke = chokes["deleted"]
	qdel(deleted)
	TEST_ASSERT(QDELETED(choke), "Удалённое тело забирает воду сразу.")

/// Течение: бесплатно и раз в 30 секунд; полоса от еретика к клетке сносит лежащих и вещи на клетку к концу, стоящего, защищённого от магии и конец не трогает; еретик на полосе быстрее; преграда обрывает полосу, новое течение заменяет старое, по сроку полоса уходит.
/datum/unit_test/heretic_tide_current/Run()
	var/turf/start = locate(run_loc_floor_bottom_left.x - 1, run_loc_floor_bottom_left.y, run_loc_floor_bottom_left.z)
	var/datum/antagonist/heretic/heretic = allocate_heretic(start)
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_current)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/eldritch_knowledge/spell/tide_current/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/spell/tide_current)
	var/obj/effect/proc_holder/spell/pointed/heretic_tide/current/spell = knowledge.granted_spell
	TEST_ASSERT(istype(spell), "Знание выдаёт Течение.")
	TEST_ASSERT_NULL(knowledge.combat_power, "Течение не выдаёт второй способности: Уйти в слив есть с первой ступени.")
	TEST_ASSERT_EQUAL(tide.dive_power.charge_max, HERETIC_TIDE_DIVE_FLOW_COOLDOWN, "Течение сокращает перезарядку Уйти в слив.")
	TEST_ASSERT_EQUAL(tide.dive_cost(), HERETIC_TIDE_DIVE_FLOW_COST, "Течение удешевляет Уйти в слив.")
	TEST_ASSERT_EQUAL(spell.charge_max, 30 SECONDS, "Перезарядка Течения 30 секунд.")
	TEST_ASSERT(!spell.can_target(locate(start.x + 9, start.y, start.z), user, TRUE), "Дальше восьми клеток течение не ложится.")
	var/turf/finish = locate(start.x + 6, start.y, start.z)
	var/mob/living/carbon/human/sleeper = allocate(/mob/living/carbon/human, locate(start.x + 1, start.y, start.z))
	sleeper.set_resting(TRUE, TRUE)
	TEST_ASSERT(!(sleeper.mobility_flags & MOBILITY_STAND), "Цель лежит.")
	var/obj/item/wrench/loose = allocate(/obj/item/wrench, locate(start.x + 3, start.y, start.z))
	var/mob/living/carbon/human/stander = allocate(/mob/living/carbon/human, locate(start.x + 5, start.y, start.z))
	var/obj/item/wrench/settled = allocate(/obj/item/wrench, finish)
	tide.combat_resource = 0
	TEST_ASSERT(tide.create_current(user, finish), "Течение ложится до указанной клетки.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 0, "Течение не стоит давления.")
	TEST_ASSERT_EQUAL(length(tide.current_cells), 7, "Полоса идёт от еретика до цели.")
	for(var/obj/effect/heretic_tide_current/cell as anything in tide.current_cells)
		TEST_ASSERT_EQUAL(cell.dir, EAST, "Течение несёт к концу полосы.")
	TEST_ASSERT(user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_sea), "На своей полосе еретик быстрее.")
	var/mob/living/carbon/human/crew = allocate(/mob/living/carbon/human, locate(start.x + 1, start.y + 2, start.z))
	var/obj/effect/heretic_tide_current/sample = tide.current_cells[2]
	TEST_ASSERT_EQUAL(sample.mouse_opacity, MOUSE_OPACITY_TRANSPARENT, "Полоса не перехватывает клики по полу.")
	var/turf/sample_turf = get_turf(sample)
	TEST_ASSERT(findtext(jointext(sample_turf.examine(crew), " "), "лежащих"), "Экипаж видит улику при осмотре пола под полосой.")
	tide.current_pulse()
	TEST_ASSERT_EQUAL(sleeper.loc, locate(start.x + 2, start.y, start.z), "Лежащего сносит на клетку к концу.")
	TEST_ASSERT_EQUAL(loose.loc, locate(start.x + 4, start.y, start.z), "Брошенную вещь сносит на клетку.")
	TEST_ASSERT_EQUAL(stander.loc, locate(start.x + 5, start.y, start.z), "Стоящего течение не сносит.")
	TEST_ASSERT_EQUAL(settled.loc, finish, "На конце полосы вещь остаётся.")
	TEST_ASSERT_EQUAL(user.loc, start, "Стоящий еретик остаётся на месте.")
	TEST_ASSERT(abs(timeleft(tide.current_expiry_timer) - HERETIC_TIDE_CURRENT_LIFETIME) <= 1, "Течение держится 20 секунд.")
	user.forceMove(locate(start.x, start.y + 1, start.z))
	TEST_ASSERT(!user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_sea), "Вне полосы ускорение пропадает.")
	var/list/old_cells = tide.current_cells.Copy()
	var/obj/blocker = allocate(/obj, locate(start.x, start.y + 4, start.z))
	blocker.density = TRUE
	TEST_ASSERT(tide.create_current(user, locate(start.x, start.y + 5, start.z)), "Новое течение ложится.")
	for(var/obj/effect/heretic_tide_current/cell as anything in old_cells)
		TEST_ASSERT(QDELETED(cell), "Новое течение заменяет старое.")
	TEST_ASSERT_EQUAL(length(tide.current_cells), 3, "Преграда обрывает полосу.")
	var/obj/effect/heretic_tide_current/last = tide.current_cells[3]
	TEST_ASSERT_EQUAL(last.loc, locate(start.x, start.y + 3, start.z), "Полоса кончается перед преградой.")
	var/turf/warded_spot = locate(start.x, start.y + 2, start.z)
	var/mob/living/carbon/human/warded = allocate(/mob/living/carbon/human, warded_spot)
	var/datum/component/anti_magic/ward = warded.AddComponent(/datum/component/anti_magic, TRUE, FALSE, FALSE, null, 5)
	warded.set_resting(TRUE, TRUE)
	tide.current_pulse()
	TEST_ASSERT_EQUAL(warded.loc, warded_spot, "Защищённого от магии лежащего течение не сносит.")
	TEST_ASSERT_EQUAL(ward.charges, 5, "Проверка течения не тратит заряды антимагии.")
	tide.clear_current()
	TEST_ASSERT_EQUAL(length(tide.current_cells), 0, "По сроку полоса уходит.")
	TEST_ASSERT(QDELETED(last), "Клетки течения удалены.")
	TEST_ASSERT(!findtext(jointext(sample_turf.examine(crew), " "), "лежащих"), "Ушедшее течение не оставляет улики на полу.")
	TEST_ASSERT(!user.has_movespeed_modifier(/datum/movespeed_modifier/heretic_tide_sea), "Ушедшее течение снимает ускорение.")

/// Уйти в слив с первой ступени: у своего прорыва за полторы секунды еретик выходит у другого своего прорыва, 2 давления и 60 секунд, с Течением 1 и 30; вдали от прорыва, к чужому источнику, к прорыву на другом уровне, без давления, из зоны без телепортации или в неё и в наручниках - отказ.
/datum/unit_test/heretic_tide_dive/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/turf/origin = get_turf(user)
	var/obj/structure/sink/near_sink = allocate(/obj/structure/sink, get_step(origin, EAST))
	var/obj/structure/sink/far_sink = allocate(/obj/structure/sink, locate(origin.x + 4, origin.y + 4, origin.z))
	var/obj/structure/sink/plain_sink = allocate(/obj/structure/sink, locate(origin.x + 4, origin.y, origin.z))
	TEST_ASSERT(tide.open_breach(near_sink, user), "Открыт ближний прорыв.")
	TEST_ASSERT(tide.open_breach(far_sink, user), "Открыт дальний прорыв.")
	var/obj/effect/proc_holder/spell/self/heretic_tide/dive/spell = tide.dive_power
	TEST_ASSERT(istype(spell) && (spell in user.mind.spell_list), "Уйти в слив есть с первой ступени.")
	TEST_ASSERT_EQUAL(spell.charge_max, HERETIC_TIDE_DIVE_COOLDOWN, "Без Течения перезарядка ухода [HERETIC_TIDE_DIVE_COOLDOWN / (1 SECONDS)] секунд.")
	TEST_ASSERT_EQUAL(HERETIC_TIDE_DIVE_COOLDOWN, 60 SECONDS, "Ранний уход перезаряжается 60 секунд.")
	TEST_ASSERT_EQUAL(HERETIC_TIDE_DIVE_FLOW_COOLDOWN, 30 SECONDS, "С Течением уход перезаряжается 30 секунд.")
	tide.combat_resource = 1
	TEST_ASSERT(!tide.dive(user, near_sink, far_sink), "Без Течения одного давления мало.")
	TEST_ASSERT(findtext(tide.tide_failure, "[HERETIC_TIDE_DIVE_COST] давления"), "Отказ называет цену: [tide.tide_failure]")
	tide.combat_resource = HERETIC_TIDE_DIVE_COST
	TEST_ASSERT(tide.dive(user, near_sink, far_sink), "Без Течения еретик уходит в слив.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 0, "Без Течения уход стоит [HERETIC_TIDE_DIVE_COST] давления.")
	TEST_ASSERT_EQUAL(get_turf(user), get_turf(far_sink), "Еретик выходит у дальнего прорыва.")
	user.forceMove(origin)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_current)
	TEST_ASSERT_EQUAL(spell.charge_max, HERETIC_TIDE_DIVE_FLOW_COOLDOWN, "С Течением перезарядка ухода [HERETIC_TIDE_DIVE_FLOW_COOLDOWN / (1 SECONDS)] секунд.")
	TEST_ASSERT(spell.charge_counter >= spell.charge_max, "Готовый уход остаётся готовым после смены перезарядки.")
	user.forceMove(locate(origin.x - 1, origin.y + 2, origin.z))
	TEST_ASSERT(!tide.dive(user, near_sink, far_sink), "Вдали от прорыва уйти нельзя.")
	TEST_ASSERT(findtext(tide.tide_failure, "вплотную"), "Отказ просит встать у прорыва: [tide.tide_failure]")
	user.forceMove(origin)
	TEST_ASSERT(!tide.dive(user, near_sink, plain_sink), "Выйти можно только у своего прорыва.")
	TEST_ASSERT(!tide.dive(user, near_sink, near_sink), "Выйти у того же прорыва нельзя.")
	var/obj/structure/sink/remote_sink = allocate(/obj/structure/sink, locate(origin.x + 2, origin.y + 4, origin.z))
	TEST_ASSERT(tide.open_breach(remote_sink, user), "Открыт третий прорыв.")
	var/turf/elsewhere = locate(origin.x, origin.y, origin.z > 1 ? origin.z - 1 : origin.z + 1)
	TEST_ASSERT_NOTNULL(elsewhere, "Есть клетка на другом уровне.")
	remote_sink.forceMove(elsewhere)
	TEST_ASSERT(!tide.dive(user, near_sink, remote_sink), "К прорыву на другом уровне в слив не уйти.")
	TEST_ASSERT(findtext(tide.tide_failure, "другом уровне"), "Отказ называет уровень: [tide.tide_failure]")
	tide.combat_resource = 0
	TEST_ASSERT(!tide.dive(user, near_sink, far_sink), "Без давления уйти нельзя.")
	TEST_ASSERT(findtext(tide.tide_failure, "давлени"), "Отказ называет давление: [tide.tide_failure]")
	tide.combat_resource = 2
	var/started = world.time
	TEST_ASSERT(tide.dive(user, near_sink, far_sink), "У своего прорыва еретик уходит в слив.")
	TEST_ASSERT(world.time - started >= 1.5 SECONDS - 0.5, "Погружение занимает полторы секунды: [world.time - started] дс.")
	TEST_ASSERT_EQUAL(get_turf(user), get_turf(far_sink), "Еретик выходит у другого прорыва.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 2 - HERETIC_TIDE_DIVE_FLOW_COST, "С Течением уход стоит [HERETIC_TIDE_DIVE_FLOW_COST] давления.")
	heretic_test_area(get_turf(far_sink), /area/unit_test_sand_noteleport)
	var/refused_at = world.time
	TEST_ASSERT(!tide.dive(user, far_sink, near_sink), "Из зоны без телепортации в слив не уйти.")
	TEST_ASSERT(findtext(tide.tide_failure, "телепорт"), "Отказ называет зону: [tide.tide_failure]")
	TEST_ASSERT_EQUAL(world.time, refused_at, "Отказ приходит сразу, без погружения.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 1, "Отказ не тратит давление.")
	user.forceMove(origin)
	TEST_ASSERT(!tide.dive(user, near_sink, far_sink), "К выходу в зоне без телепортации в слив не уйти.")
	TEST_ASSERT(findtext(tide.tide_failure, "телепорт"), "Отказ называет зону выхода: [tide.tide_failure]")
	user.handcuffed = allocate(/obj/item/restraints/handcuffs, user)
	user.update_handcuffed()
	TEST_ASSERT(!tide.dive(user, far_sink, near_sink), "В наручниках в слив не уйти.")
	TEST_ASSERT(findtext(tide.tide_failure, "наручниках"), "Отказ называет наручники: [tide.tide_failure]")
	user.uncuff()

/// Вода смыкается секунду: цель ещё говорит, сошедшая с клетки не захлёбывается и давление не возвращается, оставшаяся на месте захлёбывается.
/datum/unit_test/heretic_tide_drown_telegraph/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_drown)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/turf/origin = get_turf(user)
	var/turf/runner_spot = locate(origin.x + 2, origin.y, origin.z)
	var/turf/stayer_spot = locate(origin.x + 2, origin.y + 2, origin.z)
	var/mob/living/carbon/human/runner = allocate(/mob/living/carbon/human, runner_spot)
	var/mob/living/carbon/human/stayer = allocate(/mob/living/carbon/human, stayer_spot)
	tide.wet_floor(runner_spot)
	tide.wet_floor(stayer_spot)
	tide.combat_resource = 4
	TEST_ASSERT(tide.drown(user, runner), "Вода смыкается вокруг первой цели.")
	TEST_ASSERT(tide.drown(user, stayer), "Вода смыкается вокруг второй цели.")
	TEST_ASSERT_EQUAL(tide.combat_resource, 0, "Давление списано сразу.")
	TEST_ASSERT_NULL(runner.has_status_effect(/datum/status_effect/heretic_tide_drowning), "Первую секунду вода только смыкается.")
	TEST_ASSERT(!HAS_TRAIT(runner, TRAIT_MUTE), "До захлёба цель ещё может крикнуть.")
	TEST_ASSERT_NOTNULL(locate(/obj/effect/temp_visual/heretic_tide/warning/drown) in runner_spot, "Смыкание воды видно заранее.")
	runner.forceMove(locate(origin.x + 2, origin.y + 1, origin.z))
	TEST_ASSERT_NOTNULL(await_tide_drowning(stayer), "Оставшаяся на месте цель захлёбывается.")
	TEST_ASSERT_NULL(runner.has_status_effect(/datum/status_effect/heretic_tide_drowning), "Сошедшая с клетки цель не захлёбывается.")
	TEST_ASSERT(!HAS_TRAIT(runner, TRAIT_MUTE), "Ушедшая цель говорит.")
	TEST_ASSERT(tide.combat_resource < 2, "Сорванный захлёб давление не возвращает: [tide.combat_resource].")
	var/datum/heretic_path/path = GLOB.heretic_paths[PATH_TIDE]
	TEST_ASSERT(findtext(path.combat_practice, "смыкается секунду") && findtext(/obj/effect/proc_holder/spell/pointed/heretic_tide/drown::desc, "секунду смыкается"), "Полигон и способность называют секунду смыкания.")

/// Вода прилива вознесения - не своя вода Пучины: по ней нет Захлебнуться и двери, а по луже от Сброса рядом - есть.
/datum/unit_test/heretic_tide_flood_not_own_water/Run()
	var/turf/start = run_loc_floor_bottom_left
	var/datum/antagonist/heretic/heretic = ascend_tide_flood(start)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_drown)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/datum/component/heretic_tide_flood/flood = user.GetComponent(/datum/component/heretic_tide_flood)
	var/turf/spot = get_step(start, EAST)
	var/mob/living/carbon/human/victim = allocate_hunt_victim(heretic, spot)
	flood.flood()
	TEST_ASSERT_EQUAL(tide_flood_puddles(spot), 1, "Прилив залил клетку цели.")
	TEST_ASSERT(!tide.on_own_water(victim) && !tide.on_wet_floor(victim), "Вода прилива - не своя вода и не мокрый пол для захлёба.")
	tide.combat_resource = 4
	TEST_ASSERT(!tide.drown(user, victim), "По воде прилива Захлебнуться нельзя.")
	TEST_ASSERT(findtext(tide.tide_failure, "мокром полу"), "Отказ называет мокрый пол: [tide.tide_failure]")
	victim.Unconscious(10 SECONDS)
	TEST_ASSERT(heretic.hunt_target_ready(victim), "Цель готова к обряду.")
	TEST_ASSERT_NULL(tide.pocket_door(user, victim), "Вода прилива не открывает дверь Пучины.")
	tide.wet_floor(spot)
	TEST_ASSERT_NOTNULL(tide.pocket_door(user, victim), "Лужа от Сброса на той же клетке дверь открывает.")

/// Начало обряда обрывает захлёб без беспамятства, даже если его срок уже вышел; невосприимчивость остаётся.
/datum/unit_test/heretic_tide_drown_sacrifice/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	heretic.selected_path = PATH_TIDE
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_tide)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_drown)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/mob/living/carbon/human/victim = allocate(/mob/living/carbon/human, get_step(get_step(user, EAST), EAST))
	tide.wet_floor(get_turf(victim))
	tide.combat_resource = 4
	TEST_ASSERT(tide.drown(user, victim), "Цель в луже захлёбывается.")
	var/datum/status_effect/heretic_tide_drowning/drowning = await_tide_drowning(victim)
	TEST_ASSERT_NOTNULL(drowning, "Цель захлёбывается.")
	drowning.duration = world.time - 1
	SEND_SIGNAL(victim, COMSIG_LIVING_HERETIC_SACRIFICE_STARTING)
	TEST_ASSERT(QDELETED(drowning), "Начало обряда обрывает захлёб.")
	TEST_ASSERT(!victim.IsUnconscious(), "Оборванный обрядом захлёб не лишает сознания.")
	TEST_ASSERT(!HAS_TRAIT(victim, TRAIT_MUTE), "Немота снята.")
	TEST_ASSERT_NOTNULL(capture_immunity(victim, "tide"), "После захлёба невосприимчивость остаётся.")

/// Дверь Пучины: цель уводится с первой секунды своего захлёба, пол изнанки для Пучины - её вода, и захлёб кончается беспамятством внутри; готовая цель - только на мокром полу; 2 секунды растолкать срывают захлёб без обморока; выходы - свои прорывы, закрытые не в счёт.
/datum/unit_test/heretic_tide_pocket_door/Run()
	allocated += new /datum/heretic_test_station_level(run_loc_floor_bottom_left.z)
	var/datum/antagonist/heretic/heretic = allocate_deed_heretic(PATH_TIDE)
	heretic.gain_knowledge(/datum/eldritch_knowledge/spell/tide_drown)
	var/mob/living/carbon/human/user = heretic.owner.current
	var/datum/eldritch_knowledge/base_tide/tide = heretic.get_knowledge(/datum/eldritch_knowledge/base_tide)
	var/turf/spot = get_step(user, EAST)
	var/mob/living/carbon/human/victim = allocate_hunt_victim(heretic, spot)
	tide.wet_floor(spot)
	TEST_ASSERT(tide.on_wet_floor(victim), "Цель стоит на мокром полу.")
	TEST_ASSERT_NULL(tide.pocket_door(user, victim), "Стоящую цель на мокром полу Пучина не уводит.")
	var/datum/status_effect/heretic_tide_drowning/drowning = victim.apply_status_effect(/datum/status_effect/heretic_tide_drowning, tide)
	TEST_ASSERT_NOTNULL(drowning, "Цель захлёбывается.")
	var/list/door = tide.pocket_door(user, victim)
	TEST_ASSERT_NOTNULL(door, "Захлёбывающуюся цель Пучина уводит в изнанку.")
	TEST_ASSERT(heretic.pocket_pull(user, victim, spot, door["time"], door["check"], door["text"]), "Дверь Пучины уводит цель.")
	TEST_ASSERT(heretic.pocket_holds(victim), "Цель в изнанке.")
	TEST_ASSERT(!QDELETED(drowning), "В своей изнанке захлёб продолжается.")
	TEST_ASSERT(tide.on_wet_floor(victim) && tide.on_own_water(user), "Весь пол своей изнанки - вода Пучины.")
	TEST_ASSERT(HAS_TRAIT(victim, TRAIT_MUTE), "Внутри цель по-прежнему немая.")
	TEST_ASSERT(heretic.hunt_target_ready(victim), "В изнанке цель держит вход, она готова к обряду.")
	drowning.duration = world.time
	TEST_ASSERT(wait_for_qdeleted(drowning, 1 SECONDS), "Захлёб заканчивается в изнанке.")
	TEST_ASSERT(victim.IsUnconscious(), "Досмотренный в изнанке захлёб кончается беспамятством.")
	TEST_ASSERT(heretic.pocket_holds(victim), "Цель без сознания остаётся в изнанке.")
	heretic.pocket.collapse("проверка")
	victim.SetUnconscious(0)
	qdel(victim.has_status_effect(/datum/status_effect/heretic_capture_knockout))
	for(var/datum/status_effect/heretic_capture_immunity/immunity as anything in victim.has_status_effect_list(/datum/status_effect/heretic_capture_immunity))
		qdel(immunity)
	drowning = victim.apply_status_effect(/datum/status_effect/heretic_tide_drowning, tide)
	TEST_ASSERT_NOTNULL(drowning, "Цель снова захлёбывается.")
	SEND_SIGNAL(victim, COMSIG_LIVING_HERETIC_CAPTURE_SHAKEN, victim)
	TEST_ASSERT(QDELETED(drowning), "Растолканную цель вода отпускает.")
	TEST_ASSERT(!victim.IsUnconscious(), "Растолканная цель не теряет сознание.")

	var/turf/dry_spot = get_step(user, NORTH)
	var/mob/living/carbon/human/cuffed = allocate(/mob/living/carbon/human, dry_spot)
	cuffed.handcuffed = allocate(/obj/item/restraints/handcuffs, cuffed)
	cuffed.update_handcuffed()
	TEST_ASSERT(heretic.hunt_target_ready(cuffed), "Скованная цель готова к обряду.")
	TEST_ASSERT_NULL(tide.pocket_door(user, cuffed), "Готовую цель на сухом полу Пучина не уводит.")
	tide.wet_floor(dry_spot)
	TEST_ASSERT_NOTNULL(tide.pocket_door(user, cuffed), "Готовую цель на мокром полу Пучина уводит.")

	var/obj/structure/sink/sink = allocate(/obj/structure/sink, locate(spot.x + 3, spot.y + 4, spot.z))
	TEST_ASSERT(tide.open_breach(sink, user), "Прорыв открыт.")
	var/list/exits = tide.pocket_exits(user)
	TEST_ASSERT_EQUAL(length(exits), 1, "Выход - свой прорыв.")
	TEST_ASSERT(findtext(exits[1], "Прорыв - "), "Выход подписан прорывом и отделом: [exits[1]]")
	TEST_ASSERT(get_dist(exits[exits[1]], sink) <= 1, "Выход у своего прорыва.")
	tide.close_breach(sink)
	TEST_ASSERT_EQUAL(length(tide.pocket_exits(user)), 0, "Закрытый прорыв больше не выход.")
